### ISSUE TITLE
Bug in parsing ssh:// urls

### ISSUE THREAD

**Issue by pravindahal** [jelmer/dulwich#1012]
`example.py`:
```python3
from dulwich.client import get_transport_and_path_from_url
from dulwich.repo import Repo

repo_path = "."
repo_url = "ssh://git@github.com:python-poetry/poetry.git"

local = Repo(repo_path)
config = local.get_config_stack()
transport, path = get_transport_and_path_from_url(repo_url, config=config)
```

The above code fails with the following error:
```python
Traceback (most recent call last):
  File "C:\Users\Admin\dulwich\example.py", line 9, in <module>
    transport, path = get_transport_and_path_from_url(repo_url, config=config)
  File "C:\Users\Admin\dulwich\dulwich\client.py", line 2287, in get_transport_and_path_from_url
    return SSHGitClient.from_parsedurl(parsed, **kwargs), parsed.path
  File "C:\Users\Admin\dulwich\dulwich\client.py", line 1740, in from_parsedurl
    print(parsedurl.port)
  File "C:\Users\Admin\.pyenv\pyenv-win\versions\3.9.13\lib\urllib\parse.py", line 178, in port
    raise ValueError(message) from None
ValueError: Port could not be cast to integer value as 'python-poetry'
```

This causes the parser to fallback to rsync parser which results in wrong hostname (`ssh` instead of `github.com`).

It seems that the underlying issue is that `urlparse` from `urllib.parse` is unable to correctly parse these types of urls:
```python
(.venv) PS C:\Users\Admin\dulwich> python
Python 3.9.13 (tags/v3.9.13:6de2ca5, May 17 2022, 16:36:42) [MSC v.1929 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> from urllib.parse import urlparse
>>> parsed = urlparse("ssh://git@github.com:python-poetry/poetry.git")
>>> parsed.port
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Users\Admin\.pyenv\pyenv-win\versions\3.9.13\lib\urllib\parse.py", line 178, in port
    raise ValueError(message) from None
ValueError: Port could not be cast to integer value as 'python-poetry'
>>>
```

**Comment by jelmer** [comment]
>> ssh://git@github.com:python-poetry/poetry.git

This is an invalid URL. Git itself itself also fails when I try to clone it:

``
% git clone ssh://git@github.com:python-poetry/poetry.git
Cloning into 'poetry'...
ssh: Could not resolve hostname github.com:python-poetry: Name or service not known
fatal: Could not read from remote repository.
``

**Comment by jelmer** [comment]
> repo_url = "ssh://git@github.com:python-poetry/poetry.git"

This is an invalid URL, and parsing it this way is correct; git itself also fails to parse it:

```
% git clone ssh://git@github.com:python-poetry/poetry.git
Cloning into 'poetry'...
ssh: Could not resolve hostname github.com:python-poetry: Name or service not known
fatal: Could not read from remote repository.
```

**Comment by jelmer** [comment]
Closing this as I think it's working correctly; please feel free to reopen if I've missed something.
