### ISSUE TITLE
pathlib support

### ISSUE THREAD

**Issue by sattlerc** [jelmer/dulwich#1074]
Suppose we are in an empty bare repository:
```
git init --bare
```
This operation gives a `TypeError` (instead of a `KeyError` as expected):
```python
import dulwich.repo
from pathlib import Path
r = dulwich.repo.Repo(Path())
r.refs.refpath(b'ref')
```
Error:
```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/noname/.local/lib/python3.10/site-packages/dulwich/refs.py", line 676, in refpath
    return os.path.join(self.path, name)
  File "/usr/lib/python3.10/posixpath.py", line 90, in join
    genericpath._check_arg_types('join', a, *p)
  File "/usr/lib/python3.10/genericpath.py", line 155, in _check_arg_types
    raise TypeError("Can't mix strings and bytes in path components") from None
TypeError: Can't mix strings and bytes in path components
```

**Comment by jelmer** [comment]
I'm open to merging PRs that adds pathlib support, but I don't believe there's anywhere in Dulwich today that promises pathlib support.

**Comment by sattlerc** [comment]
I guess I was mislead by [this](https://github.com/jelmer/dulwich/blob/eb409c082b7fd173c9633b481c67e96331083062/dulwich/refs.py#L614-L615):
```python
        if getattr(path, "encode", None) is not None:
            path = os.fsencode(path)
```

**Comment by jelmer** [comment]
Ah, I see. That's meant for plain str since RefsContainer uses bytes internally.

**Comment by sattlerc** [comment]
I'm not clear about whether file paths in the API should be bytes or str. Is there a general convention? The functions themselves generally don't say.
* Some functions only work with str, for example the constructor of `Index` (this only becomes clear when looking at `Index.__repr__`, which does string formatting).
* Some functions work both with bytes and str, for example `FilePackIndex`. However, it is not clear to me whether the bytes functionality is intended or officially supported.
* Some code seems designed to officially support both bytes and str, for example [this bit](https://github.com/jelmer/dulwich/blob/1997f839a022252a607d6dff033bdd52f62fff41/dulwich/file.py#L145-L148) and lots of (unnecessary) checks whether something is bytes before calling `os.fsencode`.

It would be nice if there was a uniform convention.

**Comment by jelmer** [comment]
It's basically:

* Porcelain tries to work with strings (and generally accepts either strings or bytes)

* Paths that live inside of git datastructures are bytes

* All other paths are os-native or accept both bytes and os-native

**Comment by sattlerc** [comment]
When you say os-native, does that mean str? For example, Repo.__init__ does not accept a bytes pth.

**Comment by jelmer** [comment]
Yep.

**Comment by nanonyme** [comment]
To be fair, using os.fspath() on inputs would probably help. It will as necessary convert pathlib objects into something you can pass further.
