### ISSUE TITLE
Restore building aarch64 wheels

### ISSUE THREAD

**Issue by danyeaw** [jelmer/dulwich#1303]
Hi, thanks so much for the great library. We are using it for [Gaphor](https://github.com/gaphor/gaphor) to resolve merge conflicts of models.

I noticed that starting in 0.22.0 that there is no longer aarch64 wheels being published. This is impacting our ability to create flatpak builds. Could we please restore them? Thanks!

**Comment by danyeaw** [comment]
Thanks @jelmer!

**Comment by jelmer** [comment]
So this doesn't actually appear to work anymore, and causes the overall CI to fail so I'm going to revert it for the moment. Help appreciated (I don't have a Mac to test on). Specifically, this is the error:

```
   + delocate-wheel --require-archs arm64 -w /private/var/folders/lr/439_fwvd3m76p9vy50d57kcc0000gn/T/cibw-run-gyc22l3v/cp38-macosx_arm64/repaired_wheel -v /private/var/folders/lr/439_fwvd3m76p9vy50d57kcc0000gn/T/cibw-run-gyc22l3v/cp38-macosx_arm64/built_wheel/dulwich-0.22.2-cp38-cp38-macosx_11_0_arm64.whl
  Fixing: /private/var/folders/lr/439_fwvd3m76p9vy50d57kcc0000gn/T/cibw-run-gyc22l3v/cp38-macosx_arm64/built_wheel/dulwich-0.22.2-cp38-cp38-macosx_11_0_arm64.whl
  Traceback (most recent call last):
    File "/private/var/folders/lr/439_fwvd3m76p9vy50d57kcc0000gn/T/cibw-run-gyc22l3v/cp38-macosx_arm64/build/venv/lib/python3.8/site-packages/delocate/delocating.py", line 789, in _calculate_minimum_wheel_name
      arch_version[arch] = max(version, version_dkt[arch])
  KeyError: 'arm64'
  
  The above exception was the direct cause of the following exception:
  
  Traceback (most recent call last):
    File "/private/var/folders/lr/439_fwvd3m76p9vy50d57kcc0000gn/T/cibw-run-gyc22l3v/cp38-macosx_arm64/build/venv/bin/delocate-wheel", line 8, in <module>
      sys.exit(main())
    File "/private/var/folders/lr/439_fwvd3m76p9vy50d57kcc0000gn/T/cibw-run-gyc22l3v/cp38-macosx_arm64/build/venv/lib/python3.8/site-packages/delocate/cmd/delocate_wheel.py", line 110, in main
      copied = delocate_wheel(
    File "/private/var/folders/lr/439_fwvd3m76p9vy50d57kcc0000gn/T/cibw-run-gyc22l3v/cp38-macosx_arm64/build/venv/lib/python3.8/site-packages/delocate/delocating.py", line 1004, in delocate_wheel
      out_wheel_fixed = _check_and_update_wheel_name(
    File "/private/var/folders/lr/439_fwvd3m76p9vy50d57kcc0000gn/T/cibw-run-gyc22l3v/cp38-macosx_arm64/build/venv/lib/python3.8/site-packages/delocate/delocating.py", line 831, in _check_and_update_wheel_name
      new_name, problematic_files = _calculate_minimum_wheel_name(
    File "/private/var/folders/lr/439_fwvd3m76p9vy50d57kcc0000gn/T/cibw-run-gyc22l3v/cp38-macosx_arm64/build/venv/lib/python3.8/site-packages/delocate/delocating.py", line 798, in _calculate_minimum_wheel_name
      raise DelocationError(
  delocate.libsana.DelocationError: Failed to find any binary with the required architecture: 'arm64'
Error: Command delocate-wheel --require-archs arm64 -w /private/var/folders/lr/439_fwvd3m76p9vy50d57kcc0000gn/T/cibw-run-gyc22l3v/cp38-macosx_arm64/repaired_wheel -v /private/var/folders/lr/439_fwvd3m76p9vy50d57kcc0000gn/T/cibw-run-gyc22l3v/cp38-macosx_arm64/built_wheel/dulwich-0.22.2-cp38-cp38-macosx_11_0_arm64.whl failed with code 1. None
```

https://github.com/jelmer/dulwich/actions/runs/9424911579/job/25965881412

**Comment by jelmer** [comment]
Whoops, sorry for the spam here from the PRs. I've basically disabled those wheels that wouldn't build. See "skip = " at the bottom of pyproject.toml for the full list.

I think we build at least some arm wheels, but not for all python versions. Help to fix the rest is very much appreciated - I don't have access to a Mac system.
