### ISSUE TITLE
AttributeError: 'FancyRepo' object has no attribute 'object_store'

### ISSUE THREAD

**Issue by rbeerster** [jelmer/dulwich#1310]
Here is an error from trying to clone a repository using klaus:
```
Error on request:
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/werkzeug/serving.py", line 363, in run_wsgi
    execute(self.server.app)
  File "/usr/local/lib/python3.9/site-packages/werkzeug/serving.py", line 326, in execute
    for data in application_iter:
  File "/usr/local/lib64/python3.9/site-packages/dulwich/web.py", line 231, in get_info_refs
    handler.handle()
  File "/usr/local/lib64/python3.9/site-packages/dulwich/server.py", line 379, in handle
    self.repo.object_store,
AttributeError: 'FancyRepo' object has no attribute 'object_store'
```
Python version 3.9.18  and klaus installed using pip.  Here is how klaus was instantiated:
```
/usr/local/bin/klaus --smarthttp /var/lib/git/repo.git/
```
It seems object_store, self.repo.get_peeled, and self.repo.refs.get_symrefs are all undefined.

**Comment by rbeerster** [comment]
Thanks, I will  open an issue there.

**Comment by jonashaag** [comment]
@jelmer has anything changed about the repo class structure recently?

**Comment by jonashaag** [comment]
Oh, the problem doesn't seem to be that the class properties have changed but that I missed to proxy the `.object_store` property and now it's required

**Comment by jelmer** [comment]
Fixed on the klaus side - closing this
