### ISSUE TITLE
tests break with git-2.46

### ISSUE THREAD

**Issue by vcunat** [jelmer/dulwich#1359]
The latest dulwich-0.22.1 regresses tests after git: 2.45.2 -> 2.46.0.

Example log:
```
======================================================================
FAIL: test_copy (tests.compat.test_pack.TestPack.test_copy)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/build/source/tests/compat/test_pack.py", line 65, in test_copy
    output = run_git_or_fail(["verify-pack", "-v", pack_path])
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/build/source/tests/compat/utils.py", line 174, in run_git_or_fail
    raise AssertionError(
AssertionError: git with args ['verify-pack', '-v', '/build/tmp955685w5/Elch'] failed with 1: stdout=b'/build/tmp955685w5/Elch.pack: bad\n' stderr=b'error: index-pack died of signal 11\n'

======================================================================
FAIL: test_delta_medium_object (tests.compat.test_pack.TestPack.test_delta_medium_object)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/build/source/tests/compat/test_pack.py", line 110, in test_delta_medium_object
    output = run_git_or_fail(["verify-pack", "-v", pack_path])
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/build/source/tests/compat/utils.py", line 174, in run_git_or_fail
    raise AssertionError(
AssertionError: git with args ['verify-pack', '-v', '/build/tmpa5fkkg6x/pack_with_deltas'] failed with 1: stdout=b'/build/tmpa5fkkg6x/pack_with_deltas.pack: bad\n' stderr=b'error: index-pack died of signal 11\n'

======================================================================
FAIL: test_deltas_work (tests.compat.test_pack.TestPack.test_deltas_work)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/build/source/tests/compat/test_pack.py", line 79, in test_deltas_work
    output = run_git_or_fail(["verify-pack", "-v", pack_path])
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/build/source/tests/compat/utils.py", line 174, in run_git_or_fail
    raise AssertionError(
AssertionError: git with args ['verify-pack', '-v', '/build/tmpde_nkvwa/pack_with_deltas'] failed with 1: stdout=b'/build/tmpde_nkvwa/pack_with_deltas.pack: bad\n' stderr=b'error: index-pack died of signal 11\n'

----------------------------------------------------------------------
Ran 1507 tests in 65.260s

FAILED (failures=3, skipped=27, expected failures=1)
```

**Comment by K900** [comment]
Looks like it's an upstream git bug, actually. I'll report it to them.

**Comment by K900** [comment]
Reported upstream: https://lore.kernel.org/git/14ec9394-a7ea-456c-800a-6a84c52e5cda@0upti.me/T/#u

**Comment by jelmer** [comment]
It's possible Dulwich is generating invalid packs in some way, though it seems like C Git should just error out in that case rather than crash.

**Comment by jelmer** [comment]
Looks like this has been fixed upstream. There is a separate issue for Dulwich to support sha256

**Comment by jelmer** [comment]
Since this is fixed upstream, I'm going to close this issue.
