### ISSUE TITLE
Some porcelain commands broken in python3

### ISSUE THREAD

**Issue by garyvdm** [jelmer/dulwich#306]
I manually tested some porcelain commands in python3. Some of them are broken.  (All were also tested in python2, and work.)

    garyvdm@garyvdm /tmp % dulwich clone https://github.com/garyvdm/htmlwrite.git
    Traceback (most recent call last):
      File "/home/garyvdm/dev/dulwich/dulwich/client.py", line 1012, in _http_request
        resp = self.opener.open(req)
      File "/usr/lib/python3.4/urllib/request.py", line 469, in open
        response = meth(req, response)
      File "/usr/lib/python3.4/urllib/request.py", line 579, in http_response
        'http', request, response, code, msg, hdrs)
      File "/usr/lib/python3.4/urllib/request.py", line 507, in error
        return self._call_chain(*args)
      File "/usr/lib/python3.4/urllib/request.py", line 441, in _call_chain
        result = func(*args)
      File "/usr/lib/python3.4/urllib/request.py", line 587, in http_error_default
        raise HTTPError(req.full_url, code, msg, hdrs, fp)
    urllib.error.HTTPError: HTTP Error 404: Not Found
    
    During handling of the above exception, another exception occurred:
    
    Traceback (most recent call last):
      File "/home/garyvdm/dev/dulwich/ve34/bin/dulwich", line 6, in <module>
        exec(compile(open(__file__).read(), __file__, 'exec'))
      File "/home/garyvdm/dev/dulwich/bin/dulwich", line 381, in <module>
        commands[cmd](sys.argv[2:])
      File "/home/garyvdm/dev/dulwich/bin/dulwich", line 181, in cmd_clone
        porcelain.clone(source, target, bare=("--bare" in opts))
      File "/home/garyvdm/dev/dulwich/dulwich/porcelain.py", line 234, in clone
        progress=errstream.write)
      File "/home/garyvdm/dev/dulwich/dulwich/client.py", line 233, in fetch
        progress)
      File "/home/garyvdm/dev/dulwich/dulwich/client.py", line 1113, in fetch_pack
        b"git-upload-pack", url)
      File "/home/garyvdm/dev/dulwich/dulwich/client.py", line 1027, in _discover_references
        resp = self._http_request(url, headers)
      File "/home/garyvdm/dev/dulwich/dulwich/client.py", line 1015, in _http_request
        raise NotGitRepository()
    dulwich.errors.NotGitRepository

    garyvdm@garyvdm /tmp % dulwich clone git@github.com:garyvdm/htmlwrite.git
    ^C%

Did nothing for a long time, and I hit ctl-c to interupt.

`dulwich fetch` gives similar errors to clone

    garyvdm@garyvdm ~/dev/dulwich (git)-[master] % dulwich log
    Traceback (most recent call last):
      File "/home/garyvdm/dev/dulwich/ve34/bin/dulwich", line 6, in <module>
        exec(compile(open(__file__).read(), __file__, 'exec'))
      File "/home/garyvdm/dev/dulwich/bin/dulwich", line 381, in <module>
        commands[cmd](sys.argv[2:])
      File "/home/garyvdm/dev/dulwich/bin/dulwich", line 101, in cmd_log
        porcelain.log(repo=path, outstream=sys.stdout)
      File "/home/garyvdm/dev/dulwich/dulwich/porcelain.py", line 378, in log
        print_commit(entry.commit, outstream)
      File "/home/garyvdm/dev/dulwich/dulwich/porcelain.py", line 291, in print_commit
        outstream.write(b"-" * 50 + b"\n")
    TypeError: must be str, not bytes

    garyvdm@garyvdm ~/dev/dulwich (git)-[master] % dulwich diff HEAD
    Traceback (most recent call last):
      File "/home/garyvdm/dev/dulwich/ve34/bin/dulwich", line 6, in <module>
        exec(compile(open(__file__).read(), __file__, 'exec'))
      File "/home/garyvdm/dev/dulwich/bin/dulwich", line 381, in <module>
        commands[cmd](sys.argv[2:])
      File "/home/garyvdm/dev/dulwich/bin/dulwich", line 113, in cmd_diff
        commit = r[commit_id]
      File "/home/garyvdm/dev/dulwich/dulwich/repo.py", line 448, in __getitem__
        type(name).__name__)
    TypeError: 'name' must be bytestring, not str

    garyvdm@garyvdm ~/dev/dulwich (git)-[master] % dulwich reset --hard 
    Traceback (most recent call last):
      File "/home/garyvdm/dev/dulwich/ve34/bin/dulwich", line 6, in <module>
        exec(compile(open(__file__).read(), __file__, 'exec'))
      File "/home/garyvdm/dev/dulwich/bin/dulwich", line 381, in <module>
        commands[cmd](sys.argv[2:])
      File "/home/garyvdm/dev/dulwich/bin/dulwich", line 252, in cmd_reset
        porcelain.reset('.', mode=mode, *args)
      File "/home/garyvdm/dev/dulwich/dulwich/porcelain.py", line 517, in reset
        tree = r[committish].tree
      File "/home/garyvdm/dev/dulwich/dulwich/repo.py", line 448, in __getitem__
        type(name).__name__)
    TypeError: 'name' must be bytestring, not str

    garyvdm@garyvdm ~/dev % dulwich daemon
    2015-05-25 19:47:07,909 INFO: Listening for TCP connections on localhost:9418

(ran git clone in a different terminal)

    2015-05-25 19:47:12,959 INFO: Handling request from ('127.0.0.1', 45675)
    2015-05-25 19:47:12,959 INFO: Handling b'git-upload-pack' request, args=[b'/home/garyvdm/dev/dulwich/', b'host=localhost:9418']
    2015-05-25 19:47:12,960 ERROR: Exception happened during processing of request from ('127.0.0.1', 45675)
    Traceback (most recent call last):
      File "/usr/lib/python3.4/socketserver.py", line 305, in _handle_request_noblock
        self.process_request(request, client_address)
      File "/usr/lib/python3.4/socketserver.py", line 331, in process_request
        self.finish_request(request, client_address)
      File "/usr/lib/python3.4/socketserver.py", line 344, in finish_request
        self.RequestHandlerClass(request, client_address, self)
      File "/home/garyvdm/dev/dulwich/dulwich/server.py", line 988, in _make_handler
        return TCPGitRequestHandler(self.handlers, *args, **kwargs)
      File "/home/garyvdm/dev/dulwich/dulwich/server.py", line 968, in __init__
        SocketServer.StreamRequestHandler.__init__(self, *args, **kwargs)
      File "/usr/lib/python3.4/socketserver.py", line 673, in __init__
        self.handle()
      File "/home/garyvdm/dev/dulwich/dulwich/server.py", line 978, in handle
        h = cls(self.server.backend, args, proto)
      File "/home/garyvdm/dev/dulwich/dulwich/server.py", line 260, in __init__
        self.repo = backend.open_repository(args[0])
      File "/home/garyvdm/dev/dulwich/dulwich/server.py", line 193, in open_repository
        abspath = os.path.abspath(os.path.join(self.root, path)) + os.sep
      File "/usr/lib/python3.4/posixpath.py", line 89, in join
        "components") from None
    TypeError: Can't mix strings and bytes in path components

**Comment by jelmer** [comment]
These should be fixed now.
