### ISSUE TITLE
Status fails every time

### ISSUE THREAD

**Issue by The-Penultimate-Defenestrator** [jelmer/dulwich#415]
The simplest example of using `git status` that I can think of fails:

```
from dulwich import porcelain as git
R=git.init('.')
git.status(R)
```

I get the following error:
```
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/private/var/mobile/Containers/Shared/AppGroup/0BE72E31-5474-44B2-9731-3686B8BF7EDC/Documents/site-packages/dulwich/porcelain.py", line 641, in status
    tracked_changes = get_tree_changes(r)
  File "/private/var/mobile/Containers/Shared/AppGroup/0BE72E31-5474-44B2-9731-3686B8BF7EDC/Documents/site-packages/dulwich/porcelain.py", line 666, in get_tree_changes
    for change in index.changes_from_tree(r.object_store, r[b'HEAD'].tree):
  File "/private/var/mobile/Containers/Shared/AppGroup/0BE72E31-5474-44B2-9731-3686B8BF7EDC/Documents/site-packages/dulwich/repo.py", line 456, in __getitem__
    return self.object_store[self.refs[name]]
  File "/private/var/mobile/Containers/Shared/AppGroup/0BE72E31-5474-44B2-9731-3686B8BF7EDC/Documents/site-packages/dulwich/refs.py", line 229, in __getitem__
    raise KeyError(name)
KeyError: 'HEAD'
```

**Comment by jelmer** [comment]
Thanks for reporting. Fixed in master.
