### ISSUE TITLE
Push to empty repository can lead to 'string + None' TypeError.

### ISSUE THREAD

**Issue by sietse** [jelmer/dulwich#429]
While using hg-git to push over SSH to a newly-created git repository in GitLab, I got a traceback that ended as follows:

      File "/usr/local/lib/python2.7/dist-packages/dulwich/client.py", line 350, in _handle_receive_pack_head
        old_sha1 + b' ' + new_sha1 + b' ' + refname + b'\0' +
    TypeError: cannot concatenate 'str' and 'NoneType' objects

I have not been able to reproduce this bug. I am posting the traceback here in case it is helpful -- that is, in case you can see from the traceback which None-case wasn't guarded against.

I do not remember if the Hg repo was created by cloning the Git repo, or whether I created the Hg repo first and then added the Git repo to its path. I do know that at some point I succeeded in pulling, and then had two initial commits in my Hg repo: both with the zero SHA commit as their parent. That is all I can recall.

Feel free to close this bug report as not helpful. Many, many thanks for making Dulwich available: I have been a very happy user, via Hg-git, for a very long time now. I think it is wonderful of you to have done this work for the community.

dulwich version: `0.11.2`
hg-git version: `0.8.5`
Mercurial version: `3.8.2`
Python version: `2.7.6`

## Speculation

From the traceback, it looks like one of the variables `new_sha1` and `refname` is None, where a print statement expects them all to be strings.

(`old_sha` cannot be the variable that is `None`: having a None on the left of the `+` operator would instead to give the message `TypeError: unsupported operand type(s) for +: 'NoneType' and 'str'`.)

## The anonymized traceback:

    USER at HOST in ~/REPO on default|master at 0
    13:26:19 ☿ hg push

    # This is the pre-push hg-outgoing hook -- SB
    comparing with git@REMOTE:REMOTE_USER/REMOTE_REPO.git
    searching for changes
    @  changeset:   0:674204520503
       bookmark:    master
       tag:         tip
       user:        USER
       date:        Wed May 25 13:26:08 2016 +0200
       summary:     Initial import

    # here comes the push command -- SB
    pushing to git@REMOTE:REMOTE_USER/REMOTE_REPO.git
    searching for changes
    fatal: The remote end hung up unexpectedly
    ** Unknown exception encountered with possibly-broken third-party extension debugshell
    ** which supports versions unknown of Mercurial.
    ** Please disable debugshell and try your action again.
    ** If that fixes the bug please report it to the extension author.
    ** Python 2.7.6 (default, Jun 22 2015, 17:58:13) [GCC 4.8.2]
    ** Mercurial Distributed SCM (version 3.8.2+20160517)
    ** Extensions loaded: rebase, extdiff, histedit, color, churn, debugshell, evolve, guestrepo, hggit, strip, mq, purge, pager, prompt, record, share, shelve, chgserver
    Traceback (most recent call last):
      File "/home/USER/lib/mercurial-main/hgext/chgserver.py", line 554, in handle
        sv.serve()
      File "/home/USER/lib/mercurial-main/mercurial/commandserver.py", line 286, in serve
        while self.serveone():
      File "/home/USER/lib/mercurial-main/mercurial/commandserver.py", line 264, in serveone
        handler(self)
      File "/home/USER/lib/mercurial-main/mercurial/commandserver.py", line 247, in runcommand
        ret = (dispatch.dispatch(req) or 0) & 255 # might return None
      File "/home/USER/lib/mercurial-main/mercurial/dispatch.py", line 125, in dispatch
        ret = _runcatch(req)
      File "/home/USER/lib/mercurial-main/mercurial/dispatch.py", line 204, in _runcatch
        return _dispatch(req)
      File "/home/USER/lib/mercurial-main/mercurial/dispatch.py", line 887, in _dispatch
        cmdpats, cmdoptions)
      File "/home/USER/lib/mercurial-main/mercurial/dispatch.py", line 632, in runcommand
        ret = _runcommand(ui, options, cmd, d)
      File "/home/USER/lib/mercurial-main/mercurial/extensions.py", line 204, in closure
        return func(*(args + a), **kw)
      File "/home/USER/lib/mercurial-main/hgext/color.py", line 502, in colorcmd
        return orig(ui_, opts, cmd, cmdfunc)
      File "/home/USER/lib/mercurial-main/mercurial/dispatch.py", line 1017, in _runcommand
        return checkargs()
      File "/home/USER/lib/mercurial-main/mercurial/dispatch.py", line 978, in checkargs
        return cmdfunc()
      File "/home/USER/lib/mercurial-main/mercurial/dispatch.py", line 884, in <lambda>
        d = lambda: util.checksignature(func)(ui, *args, **cmdoptions)
      File "/home/USER/lib/mercurial-main/mercurial/util.py", line 1005, in check
        return func(*args, **kwargs)
      File "/home/USER/lib/mercurial-main/mercurial/extensions.py", line 204, in closure
        return func(*(args + a), **kw)
      File "/home/USER/lib/mercurial-main/mercurial/util.py", line 1005, in check
        return func(*args, **kwargs)
      File "/home/USER/lib/mercurial-main/hgext/mq.py", line 3519, in mqcommand
        return orig(ui, repo, *args, **kwargs)
      File "/home/USER/lib/mercurial-main/mercurial/util.py", line 1005, in check
        return func(*args, **kwargs)
      File "/home/USER/lib/mercurial-main/mercurial/extensions.py", line 204, in closure
        return func(*(args + a), **kw)
      File "/home/USER/lib/mercurial-main/mercurial/util.py", line 1005, in check
        return func(*args, **kwargs)
      File "/home/USER/dotfiles/hg/hg-prompt/prompt.py", line 446, in _push_with_cache
        res = orig(ui, repo, *args, **opts)
      File "/home/USER/lib/mercurial-main/mercurial/util.py", line 1005, in check
        return func(*args, **kwargs)
      File "/home/USER/lib/mercurial-main/mercurial/extensions.py", line 204, in closure
        return func(*(args + a), **kw)
      File "/home/USER/lib/mercurial-main/mercurial/util.py", line 1005, in check
        return func(*args, **kwargs)
      File "/home/USER/lib/hg-evolve/hgext/evolve.py", line 735, in warnobserrors
        ret = orig(ui, repo, *args, **kwargs)
      File "/home/USER/lib/mercurial-main/mercurial/util.py", line 1005, in check
        return func(*args, **kwargs)
      File "/home/USER/lib/mercurial-main/mercurial/commands.py", line 5944, in push
        opargs=opts.get('opargs'))
      File "/home/USER/lib/mercurial-main/mercurial/extensions.py", line 204, in closure
        return func(*(args + a), **kw)
      File "/home/USER/lib/hg-evolve/hgext/evolve.py", line 758, in push
        return orig(repo, *args, **opts)
      File "/home/USER/lib/mercurial-main/mercurial/extensions.py", line 204, in closure
        return func(*(args + a), **kw)
      File "/home/USER/dotfiles/hg/hg-git/hggit/util.py", line 52, in inner
        return f(*args, **kwargs)
      File "/home/USER/dotfiles/hg/hg-git/hggit/__init__.py", line 361, in exchangepush
        pushop.cgresult = repo.githandler.push(remote.path, revs, force)
      File "/home/USER/dotfiles/hg/hg-git/hggit/git_handler.py", line 343, in push
        old_refs, new_refs = self.upload_pack(remote, revs, force)
      File "/home/USER/dotfiles/hg/hg-git/hggit/git_handler.py", line 1025, in upload_pack
        progress=callback)
      File "/usr/local/lib/python2.7/dist-packages/dulwich/client.py", line 521, in send_pack
        proto, negotiated_capabilities, old_refs, new_refs)
      File "/usr/local/lib/python2.7/dist-packages/dulwich/client.py", line 350, in _handle_receive_pack_head
        old_sha1 + b' ' + new_sha1 + b' ' + refname + b'\0' +
    TypeError: cannot concatenate 'str' and 'NoneType' objects

**Comment by jelmer** [comment]
Hoi Sietse!

(Answering in English rather than Dutch so others reading this issue
can follow it).

Thanks for the bug report.

As far as I can tell this issue can only occur when hg-git is passing
None in (which is invalid), which would mean this is a Hg-Git rather than a
Dulwich bug.

That said, Dulwich should be raising a more useful exception in this
case. I'll make some changes to address this.

Cheers,

Jelmer

**Comment by jelmer** [comment]
I've added typechecks. Please try again with HEAD for improved error messages.
