### ISSUE TITLE
certificate verify failed

### ISSUE THREAD

**Issue by Salamafet** [jelmer/dulwich#447]
Hello,

When I try to clone git from HTTPS I got this error:

```
Traceback (most recent call last):
  File "C:\Python35\lib\urllib\request.py", line 1254, in do_open
    h.request(req.get_method(), req.selector, req.data, headers)
  File "C:\Python35\lib\http\client.py", line 1106, in request
    self._send_request(method, url, body, headers)
  File "C:\Python35\lib\http\client.py", line 1151, in _send_request
    self.endheaders(body)
  File "C:\Python35\lib\http\client.py", line 1102, in endheaders
    self._send_output(message_body)
  File "C:\Python35\lib\http\client.py", line 934, in _send_output
    self.send(msg)
  File "C:\Python35\lib\http\client.py", line 877, in send
    self.connect()
  File "C:\Python35\lib\http\client.py", line 1260, in connect
    server_hostname=server_hostname)
  File "C:\Python35\lib\ssl.py", line 377, in wrap_socket
    _context=self)
  File "C:\Python35\lib\ssl.py", line 752, in __init__
    self.do_handshake()
  File "C:\Python35\lib\ssl.py", line 988, in do_handshake
    self._sslobj.do_handshake()
  File "C:\Python35\lib\ssl.py", line 633, in do_handshake
    self._sslobj.do_handshake()
ssl.SSLError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:645)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\CloudStation\Python\QT\RCAB\test.py", line 10, in <module>
    porcelain.clone(depot_maj, "test")
  File "C:\Python35\lib\site-packages\dulwich\porcelain.py", line 261, in clone
    progress=errstream.write)
  File "C:\Python35\lib\site-packages\dulwich\client.py", line 256, in fetch
    progress)
  File "C:\Python35\lib\site-packages\dulwich\client.py", line 1107, in fetch_pack
    b"git-upload-pack", url)
  File "C:\Python35\lib\site-packages\dulwich\client.py", line 1007, in _discover_references
    resp = self._http_request(url, headers)
  File "C:\Python35\lib\site-packages\dulwich\client.py", line 991, in _http_request
    resp = self.opener.open(req)
  File "C:\Python35\lib\urllib\request.py", line 466, in open
    response = self._open(req, data)
  File "C:\Python35\lib\urllib\request.py", line 484, in _open
    '_open', req)
  File "C:\Python35\lib\urllib\request.py", line 444, in _call_chain
    result = func(*args)
  File "C:\Python35\lib\urllib\request.py", line 1297, in https_open
    context=self._context, check_hostname=self._check_hostname)
  File "C:\Python35\lib\urllib\request.py", line 1256, in do_open
    raise URLError(err)
urllib.error.URLError: <urlopen error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:645)>
```

I run Python 3.5 on Windows

**Comment by jelmer** [comment]
Please provide more information - what is the host you're trying to clone from?

**Comment by Salamafet** [comment]
It's my gitlab server.
I try to clone this project -> https://git.zorio.fr/UPDATE_SERVICE/RCAB

**Comment by jelmer** [comment]
Does a regular python urllib.open() to that server work ?

**Comment by Salamafet** [comment]
Same error

**Comment by jelmer** [comment]
In that case, this is not a Dulwich issue but probably something in your Python environment. Is it loading all CAs correctly?

**Comment by Salamafet** [comment]
How I can check that ?

**Comment by jelmer** [comment]
Sorry, I have no idea, I don't have Windows. I would suggest asking on one of the Python community channels - e.g. https://www.python.org/community/  or something like stackoverflow.

**Comment by Salamafet** [comment]
Fixed with this two line:

```python
import ssl
ssl._create_default_https_context = ssl._create_unverified_context
```

**Comment by jelmer** [comment]
That disables certificate checking, which opens you up to various attacks.

**Comment by Salamafet** [comment]
Yes I know. This is the only solution I found.
This is a problem with Windows and OpenSSL.
