### ISSUE TITLE
Wrong error message when socket connection is not establishing

### ISSUE THREAD

**Issue by ardumont** [jelmer/dulwich#459]
Hello, 

for supposedly internal reasons, establishing the socket connection does not work when trying to fetch pack from a remote repository.
The thing is that then the error message is not about that.
It raises an UnboundLocalError and the initial error message is not provided.

Here is an extract of the stack trace:

```
Oct 26 14:09:31 uffizi python3[16259]: [2016-10-26 14:09:31,108: ERROR/MainProcess] Task swh.loader.git.tasks.ReaderGitRepository[a9df82ad-802f-4271-8c49-73d8ed4e4746] raised unexpected: UnboundLocalError("local variable 'err' referenced before assignment",)
Oct 26 14:09:31 uffizi python3[16259]: Traceback (most recent call last):
Oct 26 14:09:31 uffizi python3[16259]: File "/usr/lib/python3/dist-packages/celery/app/trace.py", line 240, in trace_task
Oct 26 14:09:31 uffizi python3[16259]: R = retval = fun(*args, **kwargs)
Oct 26 14:09:31 uffizi python3[16259]: File "/usr/lib/python3/dist-packages/celery/app/trace.py", line 437, in __protected_call__
Oct 26 14:09:31 uffizi python3[16259]: return self.run(*args, **kwargs)
Oct 26 14:09:31 uffizi python3[16259]: File "/usr/lib/python3/dist-packages/swh/loader/git/tasks.py", line 53, in run
Oct 26 14:09:31 uffizi python3[16259]: return loader.load(repo_url)
Oct 26 14:09:31 uffizi python3[16259]: File "/usr/lib/python3/dist-packages/swh/loader/git/reader.py", line 157, in load
Oct 26 14:09:31 uffizi python3[16259]: self.fetch_data()
Oct 26 14:09:31 uffizi python3[16259]: File "/usr/lib/python3/dist-packages/swh/loader/git/updater.py", line 303, in fetch_data
Oct 26 14:09:31 uffizi python3[16259]: do_progress)
Oct 26 14:09:31 uffizi python3[16259]: File "/usr/lib/python3/dist-packages/swh/loader/git/updater.py", line 232, in fetch_pack_from_origin
Oct 26 14:09:31 uffizi python3[16259]: progress=do_activity)
Oct 26 14:09:31 uffizi python3[16259]: File "/usr/lib/python3/dist-packages/dulwich/client.py", line 555, in fetch_pack
Oct 26 14:09:31 uffizi python3[16259]: proto, can_read = self._connect(b'upload-pack', path)
Oct 26 14:09:31 uffizi python3[16259]: File "/usr/lib/python3/dist-packages/dulwich/client.py", line 643, in _connect
Oct 26 14:09:31 uffizi python3[16259]: raise err
Oct 26 14:09:31 uffizi python3[16259]: UnboundLocalError: local variable 'err' referenced before assignment
```

Running on debian jessie, the dulwich version is:

```
ardumont@uffizi:~% dpkg -l | grep dulwich
ii  python3-dulwich                0.12.0-1~bpo8+1~swh+1            amd64        Python Git library - Python3 module
```

But i can see the actual code is the same on the current master branch - https://github.com/jelmer/dulwich/blob/master/dulwich/client.py#L668-L680.

Renaming the variable from err to err_msg gives me back the initial error.

```
Oct 26 14:34:58 uffizi python3[20844]: [2016-10-26 14:34:58,657: ERROR/MainProcess] Task swh.loader.git.tasks.ReaderGitRepository[a1576e42-e251-4e21-b1bb-4be1b0c0a093] raised unexpected: OSError('no address found for github.com',)
Oct 26 14:34:58 uffizi python3[20844]: Traceback (most recent call last):
Oct 26 14:34:58 uffizi python3[20844]: File "/usr/lib/python3/dist-packages/celery/app/trace.py", line 240, in trace_task
Oct 26 14:34:58 uffizi python3[20844]: R = retval = fun(*args, **kwargs)
Oct 26 14:34:58 uffizi python3[20844]: File "/usr/lib/python3/dist-packages/celery/app/trace.py", line 437, in __protected_call__
Oct 26 14:34:58 uffizi python3[20844]: return self.run(*args, **kwargs)
Oct 26 14:34:58 uffizi python3[20844]: File "/usr/lib/python3/dist-packages/swh/loader/git/tasks.py", line 53, in run
Oct 26 14:34:58 uffizi python3[20844]: return loader.load(repo_url)
Oct 26 14:34:58 uffizi python3[20844]: File "/usr/lib/python3/dist-packages/swh/loader/git/reader.py", line 157, in load
Oct 26 14:34:58 uffizi python3[20844]: self.fetch_data()
Oct 26 14:34:58 uffizi python3[20844]: File "/usr/lib/python3/dist-packages/swh/loader/git/updater.py", line 303, in fetch_data
Oct 26 14:34:58 uffizi python3[20844]: do_progress)
Oct 26 14:34:58 uffizi python3[20844]: File "/usr/lib/python3/dist-packages/swh/loader/git/updater.py", line 232, in fetch_pack_from_origin
Oct 26 14:34:58 uffizi python3[20844]: progress=do_activity)
Oct 26 14:34:58 uffizi python3[20844]: File "/usr/lib/python3/dist-packages/dulwich/client.py", line 555, in fetch_pack
Oct 26 14:34:58 uffizi python3[20844]: proto, can_read = self._connect(b'upload-pack', path)
Oct 26 14:34:58 uffizi python3[20844]: File "/usr/lib/python3/dist-packages/dulwich/client.py", line 643, in _connect
Oct 26 14:34:58 uffizi python3[20844]: raise err_msg
Oct 26 14:34:58 uffizi python3[20844]: OSError: no address found for github.com
```

(And indeed, it's internal reasons which makes the connection fails :)

So i guess, the `try..except` inside the for loop garbles the initial `err` variable somehow.
(i could also have removed the `as err` altogether since it's not used in the except block...).

I can propose a patch if you are interested.

Thanks for dulwich, btw.

Cheers,

**Comment by ardumont** [comment]
With the second implementation (removing the unused `as err`), runtime is still ok.
The right error message is raised:

```
Oct 26 14:59:15 uffizi python3[24726]: [2016-10-26 14:59:15,171: ERROR/MainProcess] Task swh.loader.git.tasks.ReaderGitRepository[67785695-3a73-48b2-b84e-c0541fd5f075] raised unexpected: OSError('no address found for github.com',)
Oct 26 14:59:15 uffizi python3[24726]: Traceback (most recent call last):
Oct 26 14:59:15 uffizi python3[24726]: File "/usr/lib/python3/dist-packages/celery/app/trace.py", line 240, in trace_task
Oct 26 14:59:15 uffizi python3[24726]: R = retval = fun(*args, **kwargs)
Oct 26 14:59:15 uffizi python3[24726]: File "/usr/lib/python3/dist-packages/celery/app/trace.py", line 437, in __protected_call__
Oct 26 14:59:15 uffizi python3[24726]: return self.run(*args, **kwargs)
Oct 26 14:59:15 uffizi python3[24726]: File "/usr/lib/python3/dist-packages/swh/loader/git/tasks.py", line 53, in run
Oct 26 14:59:15 uffizi python3[24726]: return loader.load(repo_url)
Oct 26 14:59:15 uffizi python3[24726]: File "/usr/lib/python3/dist-packages/swh/loader/git/reader.py", line 157, in load
Oct 26 14:59:15 uffizi python3[24726]: self.fetch_data()
Oct 26 14:59:15 uffizi python3[24726]: File "/usr/lib/python3/dist-packages/swh/loader/git/updater.py", line 303, in fetch_data
Oct 26 14:59:15 uffizi python3[24726]: do_progress)
Oct 26 14:59:15 uffizi python3[24726]: File "/usr/lib/python3/dist-packages/swh/loader/git/updater.py", line 232, in fetch_pack_from_origin
Oct 26 14:59:15 uffizi python3[24726]: progress=do_activity)
Oct 26 14:59:15 uffizi python3[24726]: File "/usr/lib/python3/dist-packages/dulwich/client.py", line 555, in fetch_pack
Oct 26 14:59:15 uffizi python3[24726]: proto, can_read = self._connect(b'upload-pack', path)
Oct 26 14:59:15 uffizi python3[24726]: File "/usr/lib/python3/dist-packages/dulwich/client.py", line 643, in _connect
Oct 26 14:59:15 uffizi python3[24726]: raise err
Oct 26 14:59:15 uffizi python3[24726]: OSError: no address found for github.com
```

**Comment by jelmer** [comment]
Thanks for the bug report!

I can't reproduce this with HEAD:

% ./bin/dulwich clone git://localhost/bla /tmp/bla
Traceback (most recent call last):
  File "./bin/dulwich", line 440, in <module>
    commands[cmd](sys.argv[2:])
  File "./bin/dulwich", line 183, in cmd_clone
    porcelain.clone(source, target, bare=("--bare" in opts))
  File "/usr/lib/python2.7/dist-packages/dulwich/porcelain.py", line 269, in clone
    progress=errstream.write)
  File "/usr/lib/python2.7/dist-packages/dulwich/client.py", line 271, in fetch
    progress)
  File "/usr/lib/python2.7/dist-packages/dulwich/client.py", line 586, in fetch_pack
    proto, can_read = self._connect(b'upload-pack', path)
  File "/usr/lib/python2.7/dist-packages/dulwich/client.py", line 680, in _connect
    raise err
socket.error: [Errno 111] Connection refused

(since I don't have a git server running on my local machine)\

The idea is that the initial assignment to 'err' is only used when there were no addresses returned by DNS. If there were addresses returned, the error from the last connection attempt is returned.

(usually, this loop will only be run once, but there are exceptions - like in the case of both an A and an AAAA record).

**Comment by ardumont** [comment]
Hello,

> I can't reproduce this with HEAD:

It is all for my benefit then ^^
(i scratched my head since i saw no initial problem with the current code as well).

Reverting my patch, i keep reproducing it though.
But as no clue as to why i see this behavior.

Firing a python3 repl, it's a tcp connection timeout which seems to trigger this (if this helps in trying to reproduce).

```
>>> import socket
>>> host='github.com'
>>> from dulwich.client import TCP_GIT_PORT
>>> TCP_GIT_PORT
9418
>>> port=TCP_GIT_PORT
>>> sockaddrs=socket.getaddrinfo(host, port, socket.AF_UNSPEC, socket.SOCK_STREAM)
>>> sockaddrs
[(<AddressFamily.AF_INET: 2>, <SocketType.SOCK_STREAM: 1>, 6, '', ('192.30.253.113', 9418))]
>>> family, socktype, proto, canonname, sockaddr = sockaddrs[0]
>>> s = socket.socket(family, socktype, proto)
>>> s.setsockopt(socket.IPPROTO_TCP, socket.TCP_NODELAY, 1)
>>> s.connect(sockaddr)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
TimeoutError: [Errno 110] Connection timed out
>>> try:
...     s.connect(sockaddr)
... except socket.error as err:
...     print(err)
...
[Errno 110] Connection timed out
```

I'm still totally lost as to why the `err` variable is not assigned... since it is!

> The idea is that the initial assignment to 'err' is only used when there were no addresses returned by DNS. If there were addresses returned, the error from the last connection attempt is returned.

I guessed as much.
But somehow, in this case, this does not behave that way.
So I preferred forwarding it to you just so you are aware of it.

> (usually, this loop will only be run once, but there are exceptions - like in the case of both an A and an AAAA record).

Thanks for the details.

--

Anyway, thanks for your time.
I think we can close this if it's not reproducible.

Cheers,

**Comment by jelmer** [comment]
Thanks. Please reopen if you do manage to reproduce this against a newer version.
