### ISSUE TITLE
HttpGitClient: special characters inside username or password gives unexpected http response 401

### ISSUE THREAD

**Issue by vholovko** [jelmer/dulwich#475]
HttpGitClient doesn't unquote given credentials before passing them over to urllib2.HTTPBasicAuthHandler.

To show it let's use an example, an URL with special characters inside the password:

https://john:Ya#1$2%3@ec2-192-168-11-11.compute-11.amazonaws.com/gitonaws/repo.git

I cannot use raw (unquoted) credentials here because it will break an URL.
So I'm quoting them and get this URL instead:

https://john:Ya%231%242%253@ec2-192-168-11-11.compute-11.amazonaws.com/gitonaws/repo.git

which is a valid one.

When this kind of URL is passed to dulwich's HttpGitClient it won't unquote it before sending it over to urllib2.
```
def from_parsedurl(cls, parsedurl, **kwargs):
    auth, host = urllib2.splituser(parsedurl.netloc)
    password = parsedurl.password
    username = parsedurl.username
    parsedurl = parsedurl._replace(netloc=host)
    return cls(urlparse.urlunparse(parsedurl),
               password=password, username=username, **kwargs)
```
Thus, when the actual header is resolved the password will be left down unquoted.

`'Basic %s' % base64.b64encode('john:Ya%231%242%253').strip()`

But resolution should look like this 

`'Basic %s' % base64.b64encode('john:Ya#1$2%3').strip()`

Original cause:
```
Traceback (most recent call last):
  File ".env/local/lib/python2.7/site-packages/dulwich/porcelain.py", line 901, in fetch
    remote_refs = client.fetch(path, r, progress=errstream.write)
  File ".env/local/lib/python2.7/site-packages/dulwich/client.py", line 280, in fetch
    progress)
  File ".env/local/lib/python2.7/site-packages/dulwich/client.py", line 1193, in fetch_pack
    b"git-upload-pack", url)
  File ".env/local/lib/python2.7/site-packages/dulwich/client.py", line 1089, in _discover_references
    resp = self._http_request(url, headers)
--- <exception caught here> ---
  File ".env/local/lib/python2.7/site-packages/dulwich/client.py", line 1073, in _http_request
    resp = self.opener.open(req)
  File "/usr/lib/python2.7/urllib2.py", line 410, in open
    response = meth(req, response)
  File "/usr/lib/python2.7/urllib2.py", line 523, in http_response
    'http', request, response, code, msg, hdrs)
  File "/usr/lib/python2.7/urllib2.py", line 442, in error
    result = self._call_chain(*args)
  File "/usr/lib/python2.7/urllib2.py", line 382, in _call_chain
    result = func(*args)
  File "/usr/lib/python2.7/urllib2.py", line 897, in http_error_401
    url, req, headers)
  File "/usr/lib/python2.7/urllib2.py", line 872, in http_error_auth_reqed
    response = self.retry_http_basic_auth(host, req, realm)
  File "/usr/lib/python2.7/urllib2.py", line 885, in retry_http_basic_auth
    return self.parent.open(req, timeout=req.timeout)
  File "/usr/lib/python2.7/urllib2.py", line 410, in open
    response = meth(req, response)
  File "/usr/lib/python2.7/urllib2.py", line 523, in http_response
    'http', request, response, code, msg, hdrs)
  File "/usr/lib/python2.7/urllib2.py", line 442, in error
    result = self._call_chain(*args)
  File "/usr/lib/python2.7/urllib2.py", line 382, in _call_chain
    result = func(*args)
  File "/usr/lib/python2.7/urllib2.py", line 897, in http_error_401
    url, req, headers)
  File "/usr/lib/python2.7/urllib2.py", line 872, in http_error_auth_reqed
    response = self.retry_http_basic_auth(host, req, realm)
  File "/usr/lib/python2.7/urllib2.py", line 885, in retry_http_basic_auth
    return self.parent.open(req, timeout=req.timeout)
  File "/usr/lib/python2.7/urllib2.py", line 410, in open
    response = meth(req, response)
  File "/usr/lib/python2.7/urllib2.py", line 523, in http_response
    'http', request, response, code, msg, hdrs)
  File "/usr/lib/python2.7/urllib2.py", line 442, in error
    result = self._call_chain(*args)
  File "/usr/lib/python2.7/urllib2.py", line 382, in _call_chain
    result = func(*args)
  File "/usr/lib/python2.7/urllib2.py", line 897, in http_error_401
    url, req, headers)
  File "/usr/lib/python2.7/urllib2.py", line 872, in http_error_auth_reqed
    response = self.retry_http_basic_auth(host, req, realm)
  File "/usr/lib/python2.7/urllib2.py", line 885, in retry_http_basic_auth
    return self.parent.open(req, timeout=req.timeout)
  File "/usr/lib/python2.7/urllib2.py", line 410, in open
    response = meth(req, response)
  File "/usr/lib/python2.7/urllib2.py", line 523, in http_response
    'http', request, response, code, msg, hdrs)
  File "/usr/lib/python2.7/urllib2.py", line 442, in error
    result = self._call_chain(*args)
  File "/usr/lib/python2.7/urllib2.py", line 382, in _call_chain
    result = func(*args)
  File "/usr/lib/python2.7/urllib2.py", line 897, in http_error_401
    url, req, headers)
  File "/usr/lib/python2.7/urllib2.py", line 872, in http_error_auth_reqed
    response = self.retry_http_basic_auth(host, req, realm)
  File "/usr/lib/python2.7/urllib2.py", line 885, in retry_http_basic_auth
    return self.parent.open(req, timeout=req.timeout)
  File "/usr/lib/python2.7/urllib2.py", line 410, in open
    response = meth(req, response)
  File "/usr/lib/python2.7/urllib2.py", line 523, in http_response
    'http', request, response, code, msg, hdrs)
  File "/usr/lib/python2.7/urllib2.py", line 442, in error
    result = self._call_chain(*args)
  File "/usr/lib/python2.7/urllib2.py", line 382, in _call_chain
    result = func(*args)
  File "/usr/lib/python2.7/urllib2.py", line 897, in http_error_401
    url, req, headers)
  File "/usr/lib/python2.7/urllib2.py", line 872, in http_error_auth_reqed
    response = self.retry_http_basic_auth(host, req, realm)
  File "/usr/lib/python2.7/urllib2.py", line 885, in retry_http_basic_auth
    return self.parent.open(req, timeout=req.timeout)
  File "/usr/lib/python2.7/urllib2.py", line 410, in open
    response = meth(req, response)
  File "/usr/lib/python2.7/urllib2.py", line 523, in http_response
    'http', request, response, code, msg, hdrs)
  File "/usr/lib/python2.7/urllib2.py", line 442, in error
    result = self._call_chain(*args)
  File "/usr/lib/python2.7/urllib2.py", line 382, in _call_chain
    result = func(*args)
  File "/usr/lib/python2.7/urllib2.py", line 897, in http_error_401
    url, req, headers)
  File "/usr/lib/python2.7/urllib2.py", line 872, in http_error_auth_reqed
    response = self.retry_http_basic_auth(host, req, realm)
  File "/usr/lib/python2.7/urllib2.py", line 885, in retry_http_basic_auth
    return self.parent.open(req, timeout=req.timeout)
  File "/usr/lib/python2.7/urllib2.py", line 410, in open
    response = meth(req, response)
  File "/usr/lib/python2.7/urllib2.py", line 523, in http_response
    'http', request, response, code, msg, hdrs)
  File "/usr/lib/python2.7/urllib2.py", line 442, in error
    result = self._call_chain(*args)
  File "/usr/lib/python2.7/urllib2.py", line 382, in _call_chain
    result = func(*args)
  File "/usr/lib/python2.7/urllib2.py", line 897, in http_error_401
    url, req, headers)
  File "/usr/lib/python2.7/urllib2.py", line 860, in http_error_auth_reqed
    headers, None)
urllib2.HTTPError: HTTP Error 401: basic auth failed
```

Strage but urllib2 were making up to 5 (a magic number of) retries that can ban your account without you knowing this ;)

What's being retrieved from dulwich:
```
Traceback (most recent call last):
  File ".env/local/lib/python2.7/site-packages/dulwich/porcelain.py", line 901, in fetch
    remote_refs = client.fetch(path, r, progress=errstream.write)
  File ".env/local/lib/python2.7/site-packages/dulwich/client.py", line 280, in fetch
    progress)
  File ".env/local/lib/python2.7/site-packages/dulwich/client.py", line 1193, in fetch_pack
    b"git-upload-pack", url)
  File ".env/local/lib/python2.7/site-packages/dulwich/client.py", line 1089, in _discover_references
    resp = self._http_request(url, headers)
  File ".env/local/lib/python2.7/site-packages/dulwich/client.py", line 1078, in _http_request
    raise GitProtocolError("unexpected http response %d" % e.code)
dulwich.errors.GitProtocolError: unexpected http response 401
```

**Comment by jelmer** [comment]
thanks, merged
