### ISSUE TITLE
Lots of breaking test-cases on windows with python 3

### ISSUE THREAD

**Issue by koenfugro** [jelmer/dulwich#493]
See below. Not sure that I will have time to look at these anytime soon, i'm taking some time off soon.

`D:\Sources\dulwich>py -3 -m unittest dulwich.tests.test_suite
.s................................................................................................................................ss.s.s.....................s.s
........................ssssssssss...............................ssssss...E.sE..................................................................................
.....................................................s..s.s.....................................................................................................
.....................................................................................................s..........................................................
..........................................................................................................EEE.................................sss.E.............
.....................................................................................................s...........EEEEEEEEEEEEEEEEEEEEEEEE..x..........s.........
...............ssssssssssssssssssssssssssss.....ssssssssssssssssssssssssssssssssssssssssssssssssssssssss..sssssssssssssssssssssssssssssssssssssssssssssss
======================================================================
ERROR: test_no_decode_encode (dulwich.tests.test_index.BuildIndexTests)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "D:\Sources\dulwich\dulwich\tests\test_index.py", line 464, in test_no_decode_encode
    repo.object_store, tree.id)
  File "D:\Sources\dulwich\dulwich\index.py", line 518, in build_index_from_tree
    honor_filemode=honor_filemode)
  File "D:\Sources\dulwich\dulwich\index.py", line 427, in build_file_from_blob
    oldstat = os.lstat(target_path)
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xc0 in position 49: invalid start byte

======================================================================
ERROR: test_symlink (dulwich.tests.test_index.BuildIndexTests)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "D:\Sources\dulwich\dulwich\tests\test_index.py", line 430, in test_symlink
    repo.object_store, tree.id)
  File "D:\Sources\dulwich\dulwich\index.py", line 518, in build_index_from_tree
    honor_filemode=honor_filemode)
  File "D:\Sources\dulwich\dulwich\index.py", line 438, in build_file_from_blob
    os.symlink(contents, target_path)
ValueError: symlink: src and dst must be the same type

======================================================================
ERROR: test_commit_no_encode_decode (dulwich.tests.test_repository.BuildRepoRootTests)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "D:\Sources\dulwich\dulwich\tests\test_repository.py", line 826, in test_commit_no_encode_decode
    r.stage(names)
  File "D:\Sources\dulwich\dulwich\repo.py", line 856, in stage
    st = os.lstat(full_path)
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xc0 in position 54: invalid start byte

======================================================================
ERROR: test_commit_no_encode_decode (dulwich.tests.test_repository.BuildRepoRootTests)
----------------------------------------------------------------------
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xc0 in position 54: invalid start byte

======================================================================
ERROR: test_commit_symlink (dulwich.tests.test_repository.BuildRepoRootTests)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "D:\Sources\dulwich\dulwich\tests\test_repository.py", line 623, in test_commit_symlink
    r.stage(['a', 'b'])
  File "D:\Sources\dulwich\dulwich\repo.py", line 864, in stage
    blob = blob_from_path_and_stat(full_path, st)
  File "D:\Sources\dulwich\dulwich\index.py", line 546, in blob_from_path_and_stat
    blob.data = os.readlink(fs_path)
TypeError: readlink() argument 1 must be str, not bytes

======================================================================
ERROR: test_submodule (dulwich.tests.test_repository.RepositoryRootTests)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "D:\Sources\dulwich\dulwich\tests\test_repository.py", line 330, in test_submodule
    rel = os.path.relpath(os.path.join(repo_dir, 'submodule'), temp_dir)
  File "C:\Python36-32\lib\ntpath.py", line 585, in relpath
    path_drive, start_drive))
ValueError: path is on mount 'D:', start on mount 'C:'

======================================================================
ERROR: test_archive (dulwich.tests.compat.test_client.DulwichMockSSHClientTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "D:\Sources\dulwich\dulwich\tests\compat\test_client.py", line 195, in test_archive
    c.archive(self._build_path(b'/server_new.export'), b'HEAD', f.write)
  File "D:\Sources\dulwich\dulwich\client.py", line 637, in archive
    proto, can_read = self._connect(b'upload-archive', path)
  File "D:\Sources\dulwich\dulwich\client.py", line 1013, in _connect
    self.host, argv, port=self.port, username=self.username)
  File "D:\Sources\dulwich\dulwich\tests\compat\test_client.py", line 326, in run_command
    stdout=subprocess.PIPE, stderr=subprocess.PIPE)
  File "C:\Python36-32\lib\subprocess.py", line 707, in __init__
    restore_signals, start_new_session)
  File "C:\Python36-32\lib\subprocess.py", line 964, in _execute_child
    args = list2cmdline(args)
  File "C:\Python36-32\lib\subprocess.py", line 461, in list2cmdline
    needquote = (" " in arg) or ("\t" in arg) or not arg
TypeError: a bytes-like object is required, not 'str'

======================================================================
ERROR: test_fetch_pack (dulwich.tests.compat.test_client.DulwichMockSSHClientTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "D:\Sources\dulwich\dulwich\tests\compat\test_client.py", line 203, in test_fetch_pack
    refs = c.fetch(self._build_path(b'/server_new.export'), dest)
  File "D:\Sources\dulwich\dulwich\client.py", line 280, in fetch
    progress)
  File "D:\Sources\dulwich\dulwich\client.py", line 601, in fetch_pack
    proto, can_read = self._connect(b'upload-pack', path)
  File "D:\Sources\dulwich\dulwich\client.py", line 1013, in _connect
    self.host, argv, port=self.port, username=self.username)
  File "D:\Sources\dulwich\dulwich\tests\compat\test_client.py", line 326, in run_command
    stdout=subprocess.PIPE, stderr=subprocess.PIPE)
  File "C:\Python36-32\lib\subprocess.py", line 707, in __init__
    restore_signals, start_new_session)
  File "C:\Python36-32\lib\subprocess.py", line 964, in _execute_child
    args = list2cmdline(args)
  File "C:\Python36-32\lib\subprocess.py", line 461, in list2cmdline
    needquote = (" " in arg) or ("\t" in arg) or not arg
TypeError: a bytes-like object is required, not 'str'

======================================================================
ERROR: test_fetch_pack_no_side_band_64k (dulwich.tests.compat.test_client.DulwichMockSSHClientTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "D:\Sources\dulwich\dulwich\tests\compat\test_client.py", line 224, in test_fetch_pack_no_side_band_64k
    refs = c.fetch(self._build_path(b'/server_new.export'), dest)
  File "D:\Sources\dulwich\dulwich\client.py", line 280, in fetch
    progress)
  File "D:\Sources\dulwich\dulwich\client.py", line 601, in fetch_pack
    proto, can_read = self._connect(b'upload-pack', path)
  File "D:\Sources\dulwich\dulwich\client.py", line 1013, in _connect
    self.host, argv, port=self.port, username=self.username)
  File "D:\Sources\dulwich\dulwich\tests\compat\test_client.py", line 326, in run_command
    stdout=subprocess.PIPE, stderr=subprocess.PIPE)
  File "C:\Python36-32\lib\subprocess.py", line 707, in __init__
    restore_signals, start_new_session)
  File "C:\Python36-32\lib\subprocess.py", line 964, in _execute_child
    args = list2cmdline(args)
  File "C:\Python36-32\lib\subprocess.py", line 461, in list2cmdline
    needquote = (" " in arg) or ("\t" in arg) or not arg
TypeError: a bytes-like object is required, not 'str'

======================================================================
ERROR: test_fetch_pack_zero_sha (dulwich.tests.compat.test_client.DulwichMockSSHClientTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "D:\Sources\dulwich\dulwich\tests\compat\test_client.py", line 235, in test_fetch_pack_zero_sha
    lambda refs: [protocol.ZERO_SHA])
  File "D:\Sources\dulwich\dulwich\client.py", line 280, in fetch
    progress)
  File "D:\Sources\dulwich\dulwich\client.py", line 601, in fetch_pack
    proto, can_read = self._connect(b'upload-pack', path)
  File "D:\Sources\dulwich\dulwich\client.py", line 1013, in _connect
    self.host, argv, port=self.port, username=self.username)
  File "D:\Sources\dulwich\dulwich\tests\compat\test_client.py", line 326, in run_command
    stdout=subprocess.PIPE, stderr=subprocess.PIPE)
  File "C:\Python36-32\lib\subprocess.py", line 707, in __init__
    restore_signals, start_new_session)
  File "C:\Python36-32\lib\subprocess.py", line 964, in _execute_child
    args = list2cmdline(args)
  File "C:\Python36-32\lib\subprocess.py", line 461, in list2cmdline
    needquote = (" " in arg) or ("\t" in arg) or not arg
TypeError: a bytes-like object is required, not 'str'

======================================================================
ERROR: test_get_refs (dulwich.tests.compat.test_client.DulwichMockSSHClientTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "D:\Sources\dulwich\dulwich\tests\compat\test_client.py", line 255, in test_get_refs
    refs = c.get_refs(self._build_path(b'/server_new.export'))
  File "D:\Sources\dulwich\dulwich\client.py", line 630, in get_refs
    proto, _ = self._connect(b'upload-pack', path)
  File "D:\Sources\dulwich\dulwich\client.py", line 1013, in _connect
    self.host, argv, port=self.port, username=self.username)
  File "D:\Sources\dulwich\dulwich\tests\compat\test_client.py", line 326, in run_command
    stdout=subprocess.PIPE, stderr=subprocess.PIPE)
  File "C:\Python36-32\lib\subprocess.py", line 707, in __init__
    restore_signals, start_new_session)
  File "C:\Python36-32\lib\subprocess.py", line 964, in _execute_child
    args = list2cmdline(args)
  File "C:\Python36-32\lib\subprocess.py", line 461, in list2cmdline
    needquote = (" " in arg) or ("\t" in arg) or not arg
TypeError: a bytes-like object is required, not 'str'

======================================================================
ERROR: test_incremental_fetch_pack (dulwich.tests.compat.test_client.DulwichMockSSHClientTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "D:\Sources\dulwich\dulwich\tests\compat\test_client.py", line 209, in test_incremental_fetch_pack
    self.test_fetch_pack()
  File "D:\Sources\dulwich\dulwich\tests\compat\test_client.py", line 203, in test_fetch_pack
    refs = c.fetch(self._build_path(b'/server_new.export'), dest)
  File "D:\Sources\dulwich\dulwich\client.py", line 280, in fetch
    progress)
  File "D:\Sources\dulwich\dulwich\client.py", line 601, in fetch_pack
    proto, can_read = self._connect(b'upload-pack', path)
  File "D:\Sources\dulwich\dulwich\client.py", line 1013, in _connect
    self.host, argv, port=self.port, username=self.username)
  File "D:\Sources\dulwich\dulwich\tests\compat\test_client.py", line 326, in run_command
    stdout=subprocess.PIPE, stderr=subprocess.PIPE)
  File "C:\Python36-32\lib\subprocess.py", line 707, in __init__
    restore_signals, start_new_session)
  File "C:\Python36-32\lib\subprocess.py", line 964, in _execute_child
    args = list2cmdline(args)
  File "C:\Python36-32\lib\subprocess.py", line 461, in list2cmdline
    needquote = (" " in arg) or ("\t" in arg) or not arg
TypeError: a bytes-like object is required, not 'str'

======================================================================
ERROR: test_send_pack (dulwich.tests.compat.test_client.DulwichMockSSHClientTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "D:\Sources\dulwich\dulwich\tests\compat\test_client.py", line 109, in test_send_pack
    self._do_send_pack()
  File "D:\Sources\dulwich\dulwich\tests\compat\test_client.py", line 106, in _do_send_pack
    src.object_store.generate_pack_contents)
  File "D:\Sources\dulwich\dulwich\client.py", line 537, in send_pack
    proto, unused_can_read = self._connect(b'receive-pack', path)
  File "D:\Sources\dulwich\dulwich\client.py", line 1013, in _connect
    self.host, argv, port=self.port, username=self.username)
  File "D:\Sources\dulwich\dulwich\tests\compat\test_client.py", line 326, in run_command
    stdout=subprocess.PIPE, stderr=subprocess.PIPE)
  File "C:\Python36-32\lib\subprocess.py", line 707, in __init__
    restore_signals, start_new_session)
  File "C:\Python36-32\lib\subprocess.py", line 964, in _execute_child
    args = list2cmdline(args)
  File "C:\Python36-32\lib\subprocess.py", line 461, in list2cmdline
    needquote = (" " in arg) or ("\t" in arg) or not arg
TypeError: a bytes-like object is required, not 'str'

======================================================================
ERROR: test_send_pack_multiple_errors (dulwich.tests.compat.test_client.DulwichMockSSHClientTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "D:\Sources\dulwich\dulwich\tests\compat\test_client.py", line 181, in test_send_pack_multiple_errors
    c.send_pack(self._build_path(b'/dest'), lambda _: sendrefs, gen_pack)
  File "D:\Sources\dulwich\dulwich\client.py", line 537, in send_pack
    proto, unused_can_read = self._connect(b'receive-pack', path)
  File "D:\Sources\dulwich\dulwich\client.py", line 1013, in _connect
    self.host, argv, port=self.port, username=self.username)
  File "D:\Sources\dulwich\dulwich\tests\compat\test_client.py", line 326, in run_command
    stdout=subprocess.PIPE, stderr=subprocess.PIPE)
  File "C:\Python36-32\lib\subprocess.py", line 707, in __init__
    restore_signals, start_new_session)
  File "C:\Python36-32\lib\subprocess.py", line 964, in _execute_child
    args = list2cmdline(args)
  File "C:\Python36-32\lib\subprocess.py", line 461, in list2cmdline
    needquote = (" " in arg) or ("\t" in arg) or not arg
TypeError: a bytes-like object is required, not 'str'

======================================================================
ERROR: test_send_pack_nothing_to_send (dulwich.tests.compat.test_client.DulwichMockSSHClientTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "D:\Sources\dulwich\dulwich\tests\compat\test_client.py", line 113, in test_send_pack_nothing_to_send
    self._do_send_pack()
  File "D:\Sources\dulwich\dulwich\tests\compat\test_client.py", line 106, in _do_send_pack
    src.object_store.generate_pack_contents)
  File "D:\Sources\dulwich\dulwich\client.py", line 537, in send_pack
    proto, unused_can_read = self._connect(b'receive-pack', path)
  File "D:\Sources\dulwich\dulwich\client.py", line 1013, in _connect
    self.host, argv, port=self.port, username=self.username)
  File "D:\Sources\dulwich\dulwich\tests\compat\test_client.py", line 326, in run_command
    stdout=subprocess.PIPE, stderr=subprocess.PIPE)
  File "C:\Python36-32\lib\subprocess.py", line 707, in __init__
    restore_signals, start_new_session)
  File "C:\Python36-32\lib\subprocess.py", line 964, in _execute_child
    args = list2cmdline(args)
  File "C:\Python36-32\lib\subprocess.py", line 461, in list2cmdline
    needquote = (" " in arg) or ("\t" in arg) or not arg
TypeError: a bytes-like object is required, not 'str'

======================================================================
ERROR: test_send_pack_one_error (dulwich.tests.compat.test_client.DulwichMockSSHClientTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "D:\Sources\dulwich\dulwich\tests\compat\test_client.py", line 163, in test_send_pack_one_error
    c.send_pack(self._build_path(b'/dest'), lambda _: sendrefs, gen_pack)
  File "D:\Sources\dulwich\dulwich\client.py", line 537, in send_pack
    proto, unused_can_read = self._connect(b'receive-pack', path)
  File "D:\Sources\dulwich\dulwich\client.py", line 1013, in _connect
    self.host, argv, port=self.port, username=self.username)
  File "D:\Sources\dulwich\dulwich\tests\compat\test_client.py", line 326, in run_command
    stdout=subprocess.PIPE, stderr=subprocess.PIPE)
  File "C:\Python36-32\lib\subprocess.py", line 707, in __init__
    restore_signals, start_new_session)
  File "C:\Python36-32\lib\subprocess.py", line 964, in _execute_child
    args = list2cmdline(args)
  File "C:\Python36-32\lib\subprocess.py", line 461, in list2cmdline
    needquote = (" " in arg) or ("\t" in arg) or not arg
TypeError: a bytes-like object is required, not 'str'

======================================================================
ERROR: test_send_remove_branch (dulwich.tests.compat.test_client.DulwichMockSSHClientTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "D:\Sources\dulwich\dulwich\tests\compat\test_client.py", line 250, in test_send_remove_branch
    c.send_pack(self._build_path(b'/dest'), lambda _: sendrefs, gen_pack)
  File "D:\Sources\dulwich\dulwich\client.py", line 537, in send_pack
    proto, unused_can_read = self._connect(b'receive-pack', path)
  File "D:\Sources\dulwich\dulwich\client.py", line 1013, in _connect
    self.host, argv, port=self.port, username=self.username)
  File "D:\Sources\dulwich\dulwich\tests\compat\test_client.py", line 326, in run_command
    stdout=subprocess.PIPE, stderr=subprocess.PIPE)
  File "C:\Python36-32\lib\subprocess.py", line 707, in __init__
    restore_signals, start_new_session)
  File "C:\Python36-32\lib\subprocess.py", line 964, in _execute_child
    args = list2cmdline(args)
  File "C:\Python36-32\lib\subprocess.py", line 461, in list2cmdline
    needquote = (" " in arg) or ("\t" in arg) or not arg
TypeError: a bytes-like object is required, not 'str'

======================================================================
ERROR: test_send_without_report_status (dulwich.tests.compat.test_client.DulwichMockSSHClientTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "D:\Sources\dulwich\dulwich\tests\compat\test_client.py", line 126, in test_send_without_report_status
    src.object_store.generate_pack_contents)
  File "D:\Sources\dulwich\dulwich\client.py", line 537, in send_pack
    proto, unused_can_read = self._connect(b'receive-pack', path)
  File "D:\Sources\dulwich\dulwich\client.py", line 1013, in _connect
    self.host, argv, port=self.port, username=self.username)
  File "D:\Sources\dulwich\dulwich\tests\compat\test_client.py", line 326, in run_command
    stdout=subprocess.PIPE, stderr=subprocess.PIPE)
  File "C:\Python36-32\lib\subprocess.py", line 707, in __init__
    restore_signals, start_new_session)
  File "C:\Python36-32\lib\subprocess.py", line 964, in _execute_child
    args = list2cmdline(args)
  File "C:\Python36-32\lib\subprocess.py", line 461, in list2cmdline
    needquote = (" " in arg) or ("\t" in arg) or not arg
TypeError: a bytes-like object is required, not 'str'

======================================================================
ERROR: test_archive (dulwich.tests.compat.test_client.DulwichSubprocessClientTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "D:\Sources\dulwich\dulwich\tests\compat\test_client.py", line 195, in test_archive
    c.archive(self._build_path(b'/server_new.export'), b'HEAD', f.write)
  File "D:\Sources\dulwich\dulwich\client.py", line 637, in archive
    proto, can_read = self._connect(b'upload-archive', path)
  File "D:\Sources\dulwich\dulwich\client.py", line 790, in _connect
    stderr=self._stderr))
  File "C:\Python36-32\lib\subprocess.py", line 707, in __init__
    restore_signals, start_new_session)
  File "C:\Python36-32\lib\subprocess.py", line 964, in _execute_child
    args = list2cmdline(args)
  File "C:\Python36-32\lib\subprocess.py", line 461, in list2cmdline
    needquote = (" " in arg) or ("\t" in arg) or not arg
TypeError: a bytes-like object is required, not 'str'

======================================================================
ERROR: test_fetch_pack (dulwich.tests.compat.test_client.DulwichSubprocessClientTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "D:\Sources\dulwich\dulwich\tests\compat\test_client.py", line 203, in test_fetch_pack
    refs = c.fetch(self._build_path(b'/server_new.export'), dest)
  File "D:\Sources\dulwich\dulwich\client.py", line 280, in fetch
    progress)
  File "D:\Sources\dulwich\dulwich\client.py", line 601, in fetch_pack
    proto, can_read = self._connect(b'upload-pack', path)
  File "D:\Sources\dulwich\dulwich\client.py", line 790, in _connect
    stderr=self._stderr))
  File "C:\Python36-32\lib\subprocess.py", line 707, in __init__
    restore_signals, start_new_session)
  File "C:\Python36-32\lib\subprocess.py", line 964, in _execute_child
    args = list2cmdline(args)
  File "C:\Python36-32\lib\subprocess.py", line 461, in list2cmdline
    needquote = (" " in arg) or ("\t" in arg) or not arg
TypeError: a bytes-like object is required, not 'str'

======================================================================
ERROR: test_fetch_pack_no_side_band_64k (dulwich.tests.compat.test_client.DulwichSubprocessClientTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "D:\Sources\dulwich\dulwich\tests\compat\test_client.py", line 224, in test_fetch_pack_no_side_band_64k
    refs = c.fetch(self._build_path(b'/server_new.export'), dest)
  File "D:\Sources\dulwich\dulwich\client.py", line 280, in fetch
    progress)
  File "D:\Sources\dulwich\dulwich\client.py", line 601, in fetch_pack
    proto, can_read = self._connect(b'upload-pack', path)
  File "D:\Sources\dulwich\dulwich\client.py", line 790, in _connect
    stderr=self._stderr))
  File "C:\Python36-32\lib\subprocess.py", line 707, in __init__
    restore_signals, start_new_session)
  File "C:\Python36-32\lib\subprocess.py", line 964, in _execute_child
    args = list2cmdline(args)
  File "C:\Python36-32\lib\subprocess.py", line 461, in list2cmdline
    needquote = (" " in arg) or ("\t" in arg) or not arg
TypeError: a bytes-like object is required, not 'str'

======================================================================
ERROR: test_fetch_pack_zero_sha (dulwich.tests.compat.test_client.DulwichSubprocessClientTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "D:\Sources\dulwich\dulwich\tests\compat\test_client.py", line 235, in test_fetch_pack_zero_sha
    lambda refs: [protocol.ZERO_SHA])
  File "D:\Sources\dulwich\dulwich\client.py", line 280, in fetch
    progress)
  File "D:\Sources\dulwich\dulwich\client.py", line 601, in fetch_pack
    proto, can_read = self._connect(b'upload-pack', path)
  File "D:\Sources\dulwich\dulwich\client.py", line 790, in _connect
    stderr=self._stderr))
  File "C:\Python36-32\lib\subprocess.py", line 707, in __init__
    restore_signals, start_new_session)
  File "C:\Python36-32\lib\subprocess.py", line 964, in _execute_child
    args = list2cmdline(args)
  File "C:\Python36-32\lib\subprocess.py", line 461, in list2cmdline
    needquote = (" " in arg) or ("\t" in arg) or not arg
TypeError: a bytes-like object is required, not 'str'

======================================================================
ERROR: test_get_refs (dulwich.tests.compat.test_client.DulwichSubprocessClientTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "D:\Sources\dulwich\dulwich\tests\compat\test_client.py", line 255, in test_get_refs
    refs = c.get_refs(self._build_path(b'/server_new.export'))
  File "D:\Sources\dulwich\dulwich\client.py", line 630, in get_refs
    proto, _ = self._connect(b'upload-pack', path)
  File "D:\Sources\dulwich\dulwich\client.py", line 790, in _connect
    stderr=self._stderr))
  File "C:\Python36-32\lib\subprocess.py", line 707, in __init__
    restore_signals, start_new_session)
  File "C:\Python36-32\lib\subprocess.py", line 964, in _execute_child
    args = list2cmdline(args)
  File "C:\Python36-32\lib\subprocess.py", line 461, in list2cmdline
    needquote = (" " in arg) or ("\t" in arg) or not arg
TypeError: a bytes-like object is required, not 'str'

======================================================================
ERROR: test_incremental_fetch_pack (dulwich.tests.compat.test_client.DulwichSubprocessClientTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "D:\Sources\dulwich\dulwich\tests\compat\test_client.py", line 209, in test_incremental_fetch_pack
    self.test_fetch_pack()
  File "D:\Sources\dulwich\dulwich\tests\compat\test_client.py", line 203, in test_fetch_pack
    refs = c.fetch(self._build_path(b'/server_new.export'), dest)
  File "D:\Sources\dulwich\dulwich\client.py", line 280, in fetch
    progress)
  File "D:\Sources\dulwich\dulwich\client.py", line 601, in fetch_pack
    proto, can_read = self._connect(b'upload-pack', path)
  File "D:\Sources\dulwich\dulwich\client.py", line 790, in _connect
    stderr=self._stderr))
  File "C:\Python36-32\lib\subprocess.py", line 707, in __init__
    restore_signals, start_new_session)
  File "C:\Python36-32\lib\subprocess.py", line 964, in _execute_child
    args = list2cmdline(args)
  File "C:\Python36-32\lib\subprocess.py", line 461, in list2cmdline
    needquote = (" " in arg) or ("\t" in arg) or not arg
TypeError: a bytes-like object is required, not 'str'

======================================================================
ERROR: test_send_pack (dulwich.tests.compat.test_client.DulwichSubprocessClientTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "D:\Sources\dulwich\dulwich\tests\compat\test_client.py", line 109, in test_send_pack
    self._do_send_pack()
  File "D:\Sources\dulwich\dulwich\tests\compat\test_client.py", line 106, in _do_send_pack
    src.object_store.generate_pack_contents)
  File "D:\Sources\dulwich\dulwich\client.py", line 537, in send_pack
    proto, unused_can_read = self._connect(b'receive-pack', path)
  File "D:\Sources\dulwich\dulwich\client.py", line 790, in _connect
    stderr=self._stderr))
  File "C:\Python36-32\lib\subprocess.py", line 707, in __init__
    restore_signals, start_new_session)
  File "C:\Python36-32\lib\subprocess.py", line 964, in _execute_child
    args = list2cmdline(args)
  File "C:\Python36-32\lib\subprocess.py", line 461, in list2cmdline
    needquote = (" " in arg) or ("\t" in arg) or not arg
TypeError: a bytes-like object is required, not 'str'

======================================================================
ERROR: test_send_pack_multiple_errors (dulwich.tests.compat.test_client.DulwichSubprocessClientTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "D:\Sources\dulwich\dulwich\tests\compat\test_client.py", line 181, in test_send_pack_multiple_errors
    c.send_pack(self._build_path(b'/dest'), lambda _: sendrefs, gen_pack)
  File "D:\Sources\dulwich\dulwich\client.py", line 537, in send_pack
    proto, unused_can_read = self._connect(b'receive-pack', path)
  File "D:\Sources\dulwich\dulwich\client.py", line 790, in _connect
    stderr=self._stderr))
  File "C:\Python36-32\lib\subprocess.py", line 707, in __init__
    restore_signals, start_new_session)
  File "C:\Python36-32\lib\subprocess.py", line 964, in _execute_child
    args = list2cmdline(args)
  File "C:\Python36-32\lib\subprocess.py", line 461, in list2cmdline
    needquote = (" " in arg) or ("\t" in arg) or not arg
TypeError: a bytes-like object is required, not 'str'

======================================================================
ERROR: test_send_pack_nothing_to_send (dulwich.tests.compat.test_client.DulwichSubprocessClientTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "D:\Sources\dulwich\dulwich\tests\compat\test_client.py", line 113, in test_send_pack_nothing_to_send
    self._do_send_pack()
  File "D:\Sources\dulwich\dulwich\tests\compat\test_client.py", line 106, in _do_send_pack
    src.object_store.generate_pack_contents)
  File "D:\Sources\dulwich\dulwich\client.py", line 537, in send_pack
    proto, unused_can_read = self._connect(b'receive-pack', path)
  File "D:\Sources\dulwich\dulwich\client.py", line 790, in _connect
    stderr=self._stderr))
  File "C:\Python36-32\lib\subprocess.py", line 707, in __init__
    restore_signals, start_new_session)
  File "C:\Python36-32\lib\subprocess.py", line 964, in _execute_child
    args = list2cmdline(args)
  File "C:\Python36-32\lib\subprocess.py", line 461, in list2cmdline
    needquote = (" " in arg) or ("\t" in arg) or not arg
TypeError: a bytes-like object is required, not 'str'

======================================================================
ERROR: test_send_pack_one_error (dulwich.tests.compat.test_client.DulwichSubprocessClientTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "D:\Sources\dulwich\dulwich\tests\compat\test_client.py", line 163, in test_send_pack_one_error
    c.send_pack(self._build_path(b'/dest'), lambda _: sendrefs, gen_pack)
  File "D:\Sources\dulwich\dulwich\client.py", line 537, in send_pack
    proto, unused_can_read = self._connect(b'receive-pack', path)
  File "D:\Sources\dulwich\dulwich\client.py", line 790, in _connect
    stderr=self._stderr))
  File "C:\Python36-32\lib\subprocess.py", line 707, in __init__
    restore_signals, start_new_session)
  File "C:\Python36-32\lib\subprocess.py", line 964, in _execute_child
    args = list2cmdline(args)
  File "C:\Python36-32\lib\subprocess.py", line 461, in list2cmdline
    needquote = (" " in arg) or ("\t" in arg) or not arg
TypeError: a bytes-like object is required, not 'str'

======================================================================
ERROR: test_send_remove_branch (dulwich.tests.compat.test_client.DulwichSubprocessClientTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "D:\Sources\dulwich\dulwich\tests\compat\test_client.py", line 250, in test_send_remove_branch
    c.send_pack(self._build_path(b'/dest'), lambda _: sendrefs, gen_pack)
  File "D:\Sources\dulwich\dulwich\client.py", line 537, in send_pack
    proto, unused_can_read = self._connect(b'receive-pack', path)
  File "D:\Sources\dulwich\dulwich\client.py", line 790, in _connect
    stderr=self._stderr))
  File "C:\Python36-32\lib\subprocess.py", line 707, in __init__
    restore_signals, start_new_session)
  File "C:\Python36-32\lib\subprocess.py", line 964, in _execute_child
    args = list2cmdline(args)
  File "C:\Python36-32\lib\subprocess.py", line 461, in list2cmdline
    needquote = (" " in arg) or ("\t" in arg) or not arg
TypeError: a bytes-like object is required, not 'str'

======================================================================
ERROR: test_send_without_report_status (dulwich.tests.compat.test_client.DulwichSubprocessClientTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "D:\Sources\dulwich\dulwich\tests\compat\test_client.py", line 126, in test_send_without_report_status
    src.object_store.generate_pack_contents)
  File "D:\Sources\dulwich\dulwich\client.py", line 537, in send_pack
    proto, unused_can_read = self._connect(b'receive-pack', path)
  File "D:\Sources\dulwich\dulwich\client.py", line 790, in _connect
    stderr=self._stderr))
  File "C:\Python36-32\lib\subprocess.py", line 707, in __init__
    restore_signals, start_new_session)
  File "C:\Python36-32\lib\subprocess.py", line 964, in _execute_child
    args = list2cmdline(args)
  File "C:\Python36-32\lib\subprocess.py", line 461, in list2cmdline
    needquote = (" " in arg) or ("\t" in arg) or not arg
TypeError: a bytes-like object is required, not 'str'

----------------------------------------------------------------------
Ran 1112 tests in 81.291s

FAILED (errors=30, skipped=164, expected failures=1)

D:\Sources\dulwich>
`

**Comment by jelmer** [comment]
On Sun, Jan 22, 2017 at 11:24:50PM -0800, koenfugro wrote:
> See below. Not sure that I will have time to look at these anytime soon, i'm taking some time off soon.
Thanks for the report.

These look like simple encoding issues.

I wish there was an easy way to have travis run on Windows, that would help
preventing regressions in this area. :-(

Jelmer

**Comment by koenfugro** [comment]
I wish there was an easy way to avoid windows altogether, but well :)

It is odd that they do support os x, but not windows (which, like it or not, still seems to be the most popular os by far).

**Comment by koenfugro** [comment]
A quick heads-up: today is my last day at my current job. In my new job, I won't be working with dulwich (at least, not immediately) so I won't be able to fix any of this anymore. I guess it's best to close this ticket for now (or hope that someone else cares enough about windows & testcases to fix it).

**Comment by jelmer** [comment]
On Thu, Mar 30, 2017 at 06:23:47AM -0700, koenfugro wrote:
> A quick heads-up: today is my last day at my current job. In my new job, I won't be working with dulwich (at least, not immediately) so I won't be able to fix any of this anymore. I guess it's best to close this ticket for now (or hope that someone else cares enough about windows & testcases to fix it).
I'll keep it open, the issue still exists. :)

Thanks for all your contributions!

**Comment by jelmer** [comment]
This is resolved in master.
