### ISSUE TITLE
Repo.stage renders the repo un-commitable if a file is staged using a fully qualified path

### ISSUE THREAD

**Issue by rpdelaney** [jelmer/dulwich#496]
Only basenames are accepted, but there's no error on `.stage()` if unacceptable input is entered. Moreover, the error message from `do_commit()` is not very helpful:

```python
bpython version 0.16 on top of Python 3.6.0 /usr/bin/python
>>> import tempfile
>>> import dulwich
>>> git_dir = tempfile.TemporaryDirectory()
>>> from dulwich.repo import Repo
>>> Repo.init(git_dir.name)
<Repo at '/tmp/tmps_0hltyt'>
>>> git_file = tempfile.NamedTemporaryFile(dir=git_dir.name, delete=False)
>>> git_file.name
'/tmp/tmps_0hltyt/tmpv91i_4es'
>>> repo = Repo(git_dir.name)
>>> repo.stage(git_file.name)
>>> repo.do_commit(b'message')
Traceback (most recent call last):
  File "<input>", line 1, in <module>
    repo.do_commit(b'message')
  File "/home/ryan/.local/lib/python3.6/site-packages/dulwich/repo.py", line 556, in do_commit
    c.tree = index.commit(self.object_store)
  File "/home/ryan/.local/lib/python3.6/site-packages/dulwich/index.py", line 311, in commit
    return commit_tree(object_store, self.iterblobs())
  File "/home/ryan/.local/lib/python3.6/site-packages/dulwich/index.py", line 351, in commit_tree
    return build_tree(b'')
  File "/home/ryan/.local/lib/python3.6/site-packages/dulwich/index.py", line 345, in build_tree
    sha = build_tree(pathjoin(path, basename))
  File "/home/ryan/.local/lib/python3.6/site-packages/dulwich/index.py", line 342, in build_tree
    for basename, entry in trees[path].items():
KeyError: b'tmp'
```

**Comment by jelmer** [comment]
FWIW This is fixed in master, where it raises a clearer exception informing you to use relative paths.

**Comment by jelmer** [comment]
(I noticed your conversation on IRC)
