### ISSUE TITLE
Empty/corrupted file in repository breaks reading object api

### ISSUE THREAD

**Issue by ardumont** [jelmer/dulwich#582]
Hello,

In the same logic as #567, `git fsck` raises errors when corrupted file exists in the repository.
But dulwich is not prepared for it and breaks on it with a TypeError.

Are you interested to check against this in the same manner as before, that is try and raise an ObjectFormatException when the case raises?

### Reproductibility

Given a repository with corrupted data:
```
cd ..
$ cd sortix-gitorious-wiki.git
$ git fsck
error: object file ./objects/99/ea0c61b44c16ddd9956f8bb58749d707d14b47 is empty
error: object file ./objects/99/ea0c61b44c16ddd9956f8bb58749d707d14b47 is empty
fatal: loose object 99ea0c61b44c16ddd9956f8bb58749d707d14b47 (stored in ./objects/99/ea0c61b44c16ddd9956f8bb58749d707d14b47) is corrupt
```

For that same repository, checking with dulwich the object `99ea0c61b44c16ddd9956f8bb58749d707d14b47`:

```sh
$ python3
Python 3.5.3 (default, Jan 19 2017, 14:11:04)
[GCC 6.3.0 20170118] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> from dulwich.repo import Repo
>>> r = Repo('.')
>>> r[b'99ea0c61b44c16ddd9956f8bb58749d707d14b47']
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/lib/python3/dist-packages/dulwich/repo.py", line 472, in __getitem__
    return self.object_store[name]
  File "/usr/lib/python3/dist-packages/dulwich/object_store.py", line 118, in __getitem__
    type_num, uncomp = self.get_raw(sha)
  File "/usr/lib/python3/dist-packages/dulwich/object_store.py", line 415, in get_raw
    ret = self._get_loose_object(hexsha)
  File "/usr/lib/python3/dist-packages/dulwich/object_store.py", line 565, in _get_loose_object
    return ShaFile.from_path(path)
  File "/usr/lib/python3/dist-packages/dulwich/objects.py", line 389, in from_path
    return cls.from_file(f)
  File "/usr/lib/python3/dist-packages/dulwich/objects.py", line 395, in from_file
    obj = cls._parse_file(f)
  File "/usr/lib/python3/dist-packages/dulwich/objects.py", line 365, in _parse_file
    if cls._is_legacy_object(map):
  File "/usr/lib/python3/dist-packages/dulwich/objects.py", line 357, in _is_legacy_object
    b0 = ord(magic[0:1])
TypeError: ord() expected a character, but string of length 0 found
```

Cheers,

**Comment by ardumont** [comment]
Starting from scratch to have a bad repository (granted, it's ugly):

```
$ git init
Initialized empty Git repository in /home/tony/dulwich-error/.git/
$ echo dulwich-error > README
$ git add .
$ git commit -m "Initial commit"
[master (root-commit) ab2c931] Initial commit
 1 file changed, 1 insertion(+)
 create mode 100644 README
$ echo '=======\nRepository to crash test corruption' >> README
$ git commit -m 'Add information to readme'
On branch master
Changes not staged for commit:
        modified:   README

no changes added to commit
$ git commit -am 'Add information to readme'
[master 353af90] Add information to readme
 1 file changed, 2 insertions(+)
$ git fsck
Checking object directories: 100% (256/256), done.
$ echo '' > .git/objects/26/0dc1c741a5de33551054434a6f93b13dab6a90
zsh: permission denied: .git/objects/26/0dc1c741a5de33551054434a6f93b13dab6a90
$ ls -lh .git/objects/26/0dc1c741a5de33551054434a6f93b13dab6a90
-r--r--r-- 1 tony tony 69 Nov 13 12:15 .git/objects/26/0dc1c741a5de33551054434a6f93b13dab6a90
$ chmod +w .git/objects/26/0dc1c741a5de33551054434a6f93b13dab6a90
$ echo '' > .git/objects/26/0dc1c741a5de33551054434a6f93b13dab6a90  # brutalize the commit
$ chmod -w .git/objects/26/0dc1c741a5de33551054434a6f93b13dab6a90
$ git fsck
error: unable to unpack 260dc1c741a5de33551054434a6f93b13dab6a90 header
fatal: loose object 260dc1c741a5de33551054434a6f93b13dab6a90 (stored in .git/objects/26/0dc1c741a5de33551054434a6f93b13dab6a90) is corrupt
$ python3
Python 3.5.3 (default, Jan 19 2017, 14:11:04)
[GCC 6.3.0 20170118] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> from dulwich.repo import Repo
>>> r = Repo('.')
>>> r[b'260dc1c741a5de33551054434a6f93b13dab6a90']
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/lib/python3/dist-packages/dulwich/repo.py", line 472, in __getitem__
    return self.object_store[name]
  File "/usr/lib/python3/dist-packages/dulwich/object_store.py", line 118, in __getitem__
    type_num, uncomp = self.get_raw(sha)
  File "/usr/lib/python3/dist-packages/dulwich/object_store.py", line 415, in get_raw
    ret = self._get_loose_object(hexsha)
  File "/usr/lib/python3/dist-packages/dulwich/object_store.py", line 565, in _get_loose_object
    return ShaFile.from_path(path)
  File "/usr/lib/python3/dist-packages/dulwich/objects.py", line 389, in from_path
    return cls.from_file(f)
  File "/usr/lib/python3/dist-packages/dulwich/objects.py", line 395, in from_file
    obj = cls._parse_file(f)
  File "/usr/lib/python3/dist-packages/dulwich/objects.py", line 365, in _parse_file
    if cls._is_legacy_object(map):
  File "/usr/lib/python3/dist-packages/dulwich/objects.py", line 358, in _is_legacy_object
    b1 = ord(magic[1:2])
TypeError: ord() expected a character, but string of length 0 found
```

Cheers,

**Comment by jelmer** [comment]
Yeah, it would be great if Dulwich could handle this more gracefully.
i.e. log a proper error message during .check()

And possibly, ignore the broken object (but call out to logging.warn)
when encountering a broken object as part of normal operation.

-- 
Jelmer Vernooĳ <jelmer@jelmer.uk>
PGP Key: https://www.jelmer.uk/D729A457.asc

**Comment by ardumont** [comment]
> Yeah, it would be great if Dulwich could handle this more gracefully.

Ok.
I'm willing to dig in and propose a patch.

I'm not so sure i understood you right though.

>  i.e. log a proper error message during .check() 

The error raised here is prior to the check call.

What i am aiming at is to add check on the file's size (`os.lstat(path).st_size == 0` or something similar).
So far, I plugged this check to the `dulwich.object_storage.DiskObjectStore._get_loose_object` method.

I don't see any logging at that location though.

> And possibly, ignore the broken object (but call out to logging.warn) when encountering a broken object as part of normal operation.

The way this is currently done naturally filters out that object (without logging though, as i don't see any logging there).

Something like:
```
    def _get_loose_object(self, sha):
        path = self._get_shafile_path(sha)
        try:
            if os.lstat(path).st_size == 0:
                return None
            return ShaFile.from_path(path)
        except (OSError, IOError) as e:
            if e.errno == errno.ENOENT:
                return None
            raise
```
Note that if path does not exist, the same error as the current implementation is raised and None is returned.

When fixing, i was under the impression that the corruption took place mainly in the `loose` objects (I'm biased by the stacktrace clearly).

Please, tell me if you think i'm missing or misunderstanding something.

Cheers,

**Comment by ardumont** [comment]
I'll open a PR so we can discuss there the implementation details.
It will be simpler :)
