### ISSUE TITLE
porcelain.push Error states param should be bytes, when it should be string

### ISSUE THREAD

**Issue by dev-dull** [jelmer/dulwich#587]
```$ python3 --version
Python 3.6.2```
```>>> dulwich.__version__
(0, 18, 6)```

```>>> porcelain.push('/tmp/foobard', b'git@github.com:dev-dull/backend_test.git', b'master')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/alastad/Library/Python/3.6/lib/python/site-packages/dulwich/porcelain.py", line 761, in push
    remote_location, config=r.get_config_stack())
  File "/Users/alastad/Library/Python/3.6/lib/python/site-packages/dulwich/client.py", line 1480, in get_transport_and_path
    if ':' in location and '@' not in location:
TypeError: a bytes-like object is required, not 'str'
>>> porcelain.push('/tmp/foobard', 'git@github.com:dev-dull/backend_test.git', b'master')
Push to ssh://git@github.com/dev-dull/backend_test.git successful.```

The error message here indicates that the git repo should be "bytes-like" when in fact it should be a string; I removed the 'b' in front of my git repo string to get the push() function to work.

**Comment by jelmer** [comment]
For clarity, porcelain should probably check the types and raise an exception.
