### ISSUE TITLE
socket timeout when i use url from config

### ISSUE THREAD

**Issue by dominiquevocat** [jelmer/dulwich#594]
I have some strange issue.

using the dulwich.py command line tool as a example but i have the same issue in my own stuff:

if i modify the cmd_push to read the remote named "x" from .git/config and use push with these parameters i get a timeout

(repoPath is set in the main block)

original:
```
class cmd_push(Command):

    def run(self, args):
        parser = optparse.OptionParser()
        options, args = parser.parse_args(args)
        if len(args) < 2:
            print("Usage: dulwich push TO-LOCATION REFSPEC..")
            sys.exit(1)
        to_location = args[0]
        refspecs = args[1:]
        porcelain.push('.', to_location, refspecs)
```

modified to read a named remote and retrieve the url as string (identical to a working string passed as command line parameter

```
class cmd_push(Command):

    def run(self, args):
        import socket #set shorter timeout while testing
        socket.setdefaulttimeout(15)
        
        parser = optparse.OptionParser()
        options, args = parser.parse_args(args)
        if len(args) < 2:
            print("Usage: dulwich push TO-LOCATION REFSPEC..")
            sys.exit(1)
        to_location = args[0]
        try:
            repo = Repo(repoPath)
            config = repo.get_config()
            remote = config.get(("remote", to_location), "url")
            print >> sys.stderr, to_location
            print >> sys.stderr, type(to_location)
        except:
            print >> sys.stderr, "we don't take a config from the .git/config but rather the passed string"
            remote = to_location
            pass #we just keep to_location
        refspecs = args[1:] #usualy master
        porcelain.push(repoPath, remote, refspecs)
```

the first one works the later one uses the same url as a string for remote but ends in a timeout and there is never ever any network activity

```
12-13-2017 17:38:09.724 ERROR ScriptRunner - stderr from '/opt/splunk/bin/python /opt/splunk/etc/apps/SA-dulwich/bin/dulwich.py push https://chti-splunk:PaSSw0rd@git.someWhere/scm/splunk/sa-dulwich.git master':  we don't take a config from the .git/config but rather the passed string
12-13-2017 17:38:24.755 ERROR ScriptRunner - stderr from '/opt/splunk/bin/python /opt/splunk/etc/apps/SA-dulwich/bin/dulwich.py push https://chti-splunk:PaSSw0rd@git.someWhere/scm/splunk/sa-dulwich.git master':  Traceback (most recent call last):
12-13-2017 17:38:24.755 ERROR ScriptRunner - stderr from '/opt/splunk/bin/python /opt/splunk/etc/apps/SA-dulwich/bin/dulwich.py push https://chti-splunk:PaSSw0rd@git.someWhere/scm/splunk/sa-dulwich.git master':    File "/opt/splunk/etc/apps/SA-dulwich/bin/dulwich.py", line 630, in <module>
12-13-2017 17:38:24.755 ERROR ScriptRunner - stderr from '/opt/splunk/bin/python /opt/splunk/etc/apps/SA-dulwich/bin/dulwich.py push https://chti-splunk:PaSSw0rd@git.someWhere/scm/splunk/sa-dulwich.git master':      cmd_kls().run(sys.argv[2:])
12-13-2017 17:38:24.755 ERROR ScriptRunner - stderr from '/opt/splunk/bin/python /opt/splunk/etc/apps/SA-dulwich/bin/dulwich.py push https://chti-splunk:PaSSw0rd@git.someWhere/scm/splunk/sa-dulwich.git master':    File "/opt/splunk/etc/apps/SA-dulwich/bin/dulwich.py", line 506, in run
12-13-2017 17:38:24.755 ERROR ScriptRunner - stderr from '/opt/splunk/bin/python /opt/splunk/etc/apps/SA-dulwich/bin/dulwich.py push https://chti-splunk:PaSSw0rd@git.someWhere/scm/splunk/sa-dulwich.git master':      porcelain.push(repoPath, remote, refspecs)
12-13-2017 17:38:24.755 ERROR ScriptRunner - stderr from '/opt/splunk/bin/python /opt/splunk/etc/apps/SA-dulwich/bin/dulwich.py push https://chti-splunk:PaSSw0rd@git.someWhere/scm/splunk/sa-dulwich.git master':    File "/opt/splunk/etc/apps/SA-dulwich/bin/dulwich/porcelain.py", line 781, in push
12-13-2017 17:38:24.755 ERROR ScriptRunner - stderr from '/opt/splunk/bin/python /opt/splunk/etc/apps/SA-dulwich/bin/dulwich.py push https://chti-splunk:PaSSw0rd@git.someWhere/scm/splunk/sa-dulwich.git master':      progress=errstream.write)
12-13-2017 17:38:24.755 ERROR ScriptRunner - stderr from '/opt/splunk/bin/python /opt/splunk/etc/apps/SA-dulwich/bin/dulwich.py push https://chti-splunk:PaSSw0rd@git.someWhere/scm/splunk/sa-dulwich.git master':    File "/opt/splunk/etc/apps/SA-dulwich/bin/dulwich/client.py", line 1358, in send_pack
12-13-2017 17:38:24.755 ERROR ScriptRunner - stderr from '/opt/splunk/bin/python /opt/splunk/etc/apps/SA-dulwich/bin/dulwich.py push https://chti-splunk:PaSSw0rd@git.someWhere/scm/splunk/sa-dulwich.git master':      b"git-receive-pack", url)
12-13-2017 17:38:24.755 ERROR ScriptRunner - stderr from '/opt/splunk/bin/python /opt/splunk/etc/apps/SA-dulwich/bin/dulwich.py push https://chti-splunk:PaSSw0rd@git.someWhere/scm/splunk/sa-dulwich.git master':    File "/opt/splunk/etc/apps/SA-dulwich/bin/dulwich/client.py", line 1284, in _discover_references
12-13-2017 17:38:24.755 ERROR ScriptRunner - stderr from '/opt/splunk/bin/python /opt/splunk/etc/apps/SA-dulwich/bin/dulwich.py push https://chti-splunk:PaSSw0rd@git.someWhere/scm/splunk/sa-dulwich.git master':      resp, read = self._http_request(url, headers, allow_compression=True)
12-13-2017 17:38:24.755 ERROR ScriptRunner - stderr from '/opt/splunk/bin/python /opt/splunk/etc/apps/SA-dulwich/bin/dulwich.py push https://chti-splunk:PaSSw0rd@git.someWhere/scm/splunk/sa-dulwich.git master':    File "/opt/splunk/etc/apps/SA-dulwich/bin/dulwich/client.py", line 1263, in _http_request
12-13-2017 17:38:24.755 ERROR ScriptRunner - stderr from '/opt/splunk/bin/python /opt/splunk/etc/apps/SA-dulwich/bin/dulwich.py push https://chti-splunk:PaSSw0rd@git.someWhere/scm/splunk/sa-dulwich.git master':      resp = self.opener.open(req)
12-13-2017 17:38:24.755 ERROR ScriptRunner - stderr from '/opt/splunk/bin/python /opt/splunk/etc/apps/SA-dulwich/bin/dulwich.py push https://chti-splunk:PaSSw0rd@git.someWhere/scm/splunk/sa-dulwich.git master':    File "/opt/splunk/lib/python2.7/urllib2.py", line 429, in open
12-13-2017 17:38:24.757 ERROR ScriptRunner - stderr from '/opt/splunk/bin/python /opt/splunk/etc/apps/SA-dulwich/bin/dulwich.py push https://chti-splunk:PaSSw0rd@git.someWhere/scm/splunk/sa-dulwich.git master':      response = self._open(req, data)
12-13-2017 17:38:24.757 ERROR ScriptRunner - stderr from '/opt/splunk/bin/python /opt/splunk/etc/apps/SA-dulwich/bin/dulwich.py push https://chti-splunk:PaSSw0rd@git.someWhere/scm/splunk/sa-dulwich.git master':    File "/opt/splunk/lib/python2.7/urllib2.py", line 447, in _open
12-13-2017 17:38:24.758 ERROR ScriptRunner - stderr from '/opt/splunk/bin/python /opt/splunk/etc/apps/SA-dulwich/bin/dulwich.py push https://chti-splunk:PaSSw0rd@git.someWhere/scm/splunk/sa-dulwich.git master':      '_open', req)
12-13-2017 17:38:24.758 ERROR ScriptRunner - stderr from '/opt/splunk/bin/python /opt/splunk/etc/apps/SA-dulwich/bin/dulwich.py push https://chti-splunk:PaSSw0rd@git.someWhere/scm/splunk/sa-dulwich.git master':    File "/opt/splunk/lib/python2.7/urllib2.py", line 407, in _call_chain
12-13-2017 17:38:24.758 ERROR ScriptRunner - stderr from '/opt/splunk/bin/python /opt/splunk/etc/apps/SA-dulwich/bin/dulwich.py push https://chti-splunk:PaSSw0rd@git.someWhere/scm/splunk/sa-dulwich.git master':      result = func(*args)
12-13-2017 17:38:24.758 ERROR ScriptRunner - stderr from '/opt/splunk/bin/python /opt/splunk/etc/apps/SA-dulwich/bin/dulwich.py push https://chti-splunk:PaSSw0rd@git.someWhere/scm/splunk/sa-dulwich.git master':    File "/opt/splunk/lib/python2.7/urllib2.py", line 1241, in https_open
12-13-2017 17:38:24.758 ERROR ScriptRunner - stderr from '/opt/splunk/bin/python /opt/splunk/etc/apps/SA-dulwich/bin/dulwich.py push https://chti-splunk:PaSSw0rd@git.someWhere/scm/splunk/sa-dulwich.git master':      context=self._context)
12-13-2017 17:38:24.758 ERROR ScriptRunner - stderr from '/opt/splunk/bin/python /opt/splunk/etc/apps/SA-dulwich/bin/dulwich.py push https://chti-splunk:PaSSw0rd@git.someWhere/scm/splunk/sa-dulwich.git master':    File "/opt/splunk/lib/python2.7/urllib2.py", line 1198, in do_open
12-13-2017 17:38:24.758 ERROR ScriptRunner - stderr from '/opt/splunk/bin/python /opt/splunk/etc/apps/SA-dulwich/bin/dulwich.py push https://chti-splunk:PaSSw0rd@git.someWhere/scm/splunk/sa-dulwich.git master':      raise URLError(err)
12-13-2017 17:38:24.758 ERROR ScriptRunner - stderr from '/opt/splunk/bin/python /opt/splunk/etc/apps/SA-dulwich/bin/dulwich.py push https://chti-splunk:PaSSw0rd@git.someWhere/scm/splunk/sa-dulwich.git master':  urllib2.URLError: <urlopen error ('_ssl.c:660: The handshake operation timed out',)>
```

huh?

also, it would be awfully nice if porcelain would to excatly this: get the remote by name from .git/config
also i would like to supply user and password during runtime reading it myself from some secure storage... and not have it in the url

dulwich is __version__ = (0, 18, 7)
python is 2.7.something

**Comment by dominiquevocat** [comment]
uh, i *think* splunk is guilty
i can workaround by doing

```
import urllib2
urllib2.getproxies = lambda: {}
```
(i do  not have set any proxies though but there might be some funky handling)

**Comment by jelmer** [comment]
If you don't have any proxies configured in your git configuration files, then this is due to some logic in urllib2 rather than Dulwich. Perhaps splunk sets a http_proxy environment variable that urllib2 picks up?

On 13 December 2017 17:49:35 GMT, dominiquevocat <notifications@github.com> wrote:
>uh, i *think* splunk is guilty
>i can workaround by doing
>
>```
>import urllib2
>urllib2.getproxies = lambda: {}
>```
>(i do  not have set any proxies though but there might be some funky
>handling)
>
>-- 
>You are receiving this because you are subscribed to this thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/jelmer/dulwich/issues/594#issuecomment-351468969

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by dominiquevocat** [comment]
the workaround addresses the issue which is splunk related (and based on our config)
solved

**Comment by zogzog** [comment]
Interesting ticket. I suspect proxy handling is less than perfect still as of today.

**Comment by jelmer** [comment]
FWIW this ticket was from before Dulwich migrated to urllib3.
