### ISSUE TITLE
Behavior change in dulwich 0.20.0 in porcelain.path_to_tree_path

### ISSUE THREAD

**Issue by Lothiraldan** [jelmer/dulwich#772]
While trying to update to dulwich 0.20.0, our test suite detected a behavior change in `porcelain.path_to_tree_path` with Python 3.4 and 3.5.

Here is a reproduction script:

```
import sys
import os.path
import tempfile
import dulwich.repo
import dulwich.porcelain

print("Python version", sys.version)
print("Dulwich version", dulwich.__version__)

tmp_path = tempfile.mkdtemp()
os.chdir(tmp_path)
repo = dulwich.repo.Repo.init(tmp_path)

repo.do_commit(b"Root").decode("utf-8")

one_commit_file_path = os.path.join(tmp_path, "file")
with open(one_commit_file_path, "w") as f:
    f.write("file")
os.chmod(one_commit_file_path, 0o644)

dulwich.porcelain.add(repo, one_commit_file_path)

repo.stage([b"file"])
repo.do_commit(b"The first commit").decode("utf-8")
os.remove(one_commit_file_path)
dulwich.porcelain.remove(repo, [one_commit_file_path])

print("OK!")
```

Here is the behavior with various Python versions:

<details>
 <summary>Python 2.7 / Dulwich 0.19.6</summary>

```
('Python version', '2.7.17 (default, Dec  2 2019, 16:40:46) \n[GCC 9.2.1 20190827 (Red Hat 9.2.1-1)]')
('Dulwich version', (0, 19, 16))
OK!
```
</details>

<details>
 <summary>Python 3.4 and Python 3.5 / Dulwich 0.19.6</summary>

```
Python version 3.4.10 (default, Dec 19 2019, 21:14:01) 
[GCC 9.2.1 20190827 (Red Hat 9.2.1-1)]
Dulwich version (0, 19, 16)
OK!
```
</details>

<details>
 <summary>Python 3.4 and Python 3.5 / Dulwich 0.19.6</summary>

```
Python version 3.4.10 (default, Dec 19 2019, 21:14:01) 
[GCC 9.2.1 20190827 (Red Hat 9.2.1-1)]
Dulwich version (0, 20, 2)
Traceback (most recent call last):
  File "dulwich_repro.py", line 26, in <module>
    dulwich.porcelain.remove(repo, [one_commit_file_path])
  File "/home/lothiraldan/.virtualenvs/venv/lib/python3.4/site-packages/dulwich/porcelain.py", line 481, in remove
    tree_path = path_to_tree_path(r.path, p)
  File "/home/lothiraldan/.virtualenvs/venv/lib/python3.4/site-packages/dulwich/porcelain.py", line 205, in path_to_tree_path
    path = Path(path).resolve()
  File "/home/lothiraldan/.pyenv/versions/3.4.10/lib/python3.4/pathlib.py", line 1044, in resolve
    s = self._flavour.resolve(self)
  File "/home/lothiraldan/.pyenv/versions/3.4.10/lib/python3.4/pathlib.py", line 300, in resolve
    return _resolve(base, str(path)) or sep
  File "/home/lothiraldan/.pyenv/versions/3.4.10/lib/python3.4/pathlib.py", line 285, in _resolve
    target = accessor.readlink(newpath)
  File "/home/lothiraldan/.pyenv/versions/3.4.10/lib/python3.4/pathlib.py", line 377, in readlink
    return os.readlink(path)
FileNotFoundError: [Errno 2] No such file or directory: '/tmp/tmpkia_wrne/file'
```
</details>

<details>
 <summary>Python 3.6+ / Dulwich 0.19.6</summary>

```
Python version 3.7.5 (default, Nov 25 2019, 10:09:43) 
[GCC 9.2.1 20190827 (Red Hat 9.2.1-1)]
Dulwich version (0, 19, 16)
OK!
```
</details>

<details>
 <summary>Python 3.6+ / Dulwich 0.20.2</summary>

```
Python version 3.7.5 (default, Nov 25 2019, 10:09:43) 
[GCC 9.2.1 20190827 (Red Hat 9.2.1-1)]
Dulwich version (0, 20, 2)
OK!
```
</details>

I've track down the behavior difference in https://docs.python.org/3/library/pathlib.html?highlight=pathlib#pathlib.Path.resolve where the behavior changed in Python 3.6. Before it used to raise FileNotFoundError is the resolved path doesn't exists on disk.

`path_to_tree_path` is used in several places and we might hit that case in various situation. I think we should add a compatiblity layer for `Path(...).resolve` to catch the FileNotFoundError in Python 3.4 and 3.5. I can sends a PR if you think this approach is correct.

Thank you again for you amazing work!

**Comment by jelmer** [comment]
Thanks for the detailed bug report!

Handling FileNotFoundError in path_to_tree_path seems reasonable to me; a PR to do that would be great.

FWIW Dulwich no longer supports Python 3.4.

**Comment by jelmer** [comment]
Ah :-/

I'm a bit hesitant about using pathlib2, since it's dead upstream and the repository is archived.

We could go back to the old code without PathLib for python 3.5? The use of resolve() is there to allow the tests to pass on Mac OS X and Windows, but they only work on Python 3.6 and up on Windows and Mac OS X anyway.

So practically speaking that would mean dropping support for Python 3.5 on any platform but Linux.

**Comment by Lothiraldan** [comment]
That could be a solution, I will investigate.

What do you mean by `dropping support for Python 3.5 on any platform but Linux`? Does dulwich 0.19.6 officially support Mac OS X and Windows?

**Comment by jelmer** [comment]
0.19.6 doesn't support Mac OS X and Windows at all; 0.20.2 does, but the tests already fail on Python 3.5 on Windows and Mac OS X and we don't provide wheels for Python 3.5 on Mac OS X and Windows. We should probably write that down somewhere though.

**Comment by jelmer** [comment]
Perhaps the the best way to start off with this is to add a test to Dulwich that reproduces the problem on Python 3.5.

**Comment by Lothiraldan** [comment]
I started a PR with a failing test: https://github.com/dulwich/dulwich/pull/777

It fails on Python 3.5 but it's expected. What was not expected is that it also failed on Windows no matter the Python version.

**Comment by jelmer** [comment]
That makes sense to me - we'd need to fall back to the old version of path_to_tree_path on Python 3.5 on Linux.

**Comment by Lothiraldan** [comment]
I found why the build is failing on Windows, if the file doesn't exists, Pathlib.resolve() returns a relative path on Windows, there is an open bug in Python: https://bugs.python.org/issue38671

**Comment by jelmer** [comment]
Ah, great. It would probably be possible to add a workaround for that bug in Dulwich, i.e. using os.path.abspath() in that situation?

**Comment by Lothiraldan** [comment]
I've updated https://github.com/dulwich/dulwich/pull/777 to make the absolute path resolving before creating the `pathlib.Path` objects which seems to make the new test happy.

I'm not sure if we should replace `Path.resolve` by `os.path.abspath` as I think they are subtle difference between the two, I add to also add a call to `os.path.abspath` on the repopath as I got different paths prefixes, for example here: https://github.com/dulwich/dulwich/runs/914872136

```
ValueError: 'C:\\Users\\RUNNER~1\\AppData\\Local\\Temp\\tmpguzhxsss\\repo\\foo' does not start with 'C:\\Users\\runneradmin\\AppData\\Local\\Temp\\tmpguzhxsss\\repo'
```

**Comment by jelmer** [comment]
On Mon, Jul 27, 2020 at 08:19:10AM -0700, Boris Feld wrote:
> I've updated https://github.com/dulwich/dulwich/pull/777 to make the absolute path resolving before creating the `pathlib.Path` objects which seems to make the new test happy.
> 
> I'm not sure if we should replace `Path.resolve` by `os.path.abspath` as I think they are subtle difference between the two, I add to also add a call to `os.path.abspath` on the repopath as I got different paths prefixes, for example here: https://github.com/dulwich/dulwich/runs/914872136
We can't - abspath isn't correct, but this is as strictly better than
what we had previously.

(There is also more to be done to make the Path.resolve call more
correct in certain situations)

-- 
Jelmer Vernooĳ <jelmer@jelmer.uk>
PGP Key: https://www.jelmer.uk/D729A457.asc

**Comment by jelmer** [comment]
We've dropped support for python 3.4 and 3.5 so I'm going to close this bug report.
