### ISSUE TITLE
Support for extra header authentication

### ISSUE THREAD

**Issue by 0x2b3bfa0** [jelmer/dulwich#882]
It would be really nice to honor the [extra header](https://git-scm.com/docs/git-config#Documentation/git-config.txt-httpextraHeader) configuration option in order to allow authentication against HTTP remotes that support [basic authentication](https://datatracker.ietf.org/doc/html/rfc7617#section-2) , like in ephemeral headless environments like continous integration runners.

For example, the official [`actions/checkout@v2`](https://github.com/actions/checkout/tree/v2) GitHub Action relies on a custom header set through the [local repository configuration](https://git-scm.com/book/en/v2/Customizing-Git-Git-Configuration#_git_config) to authenticate against the remote:

```ini
[http "https://github.com/"]
        extraheader = AUTHORIZATION: basic ···
```

### Minimal example

```python3
>>> from dulwich.porcelain import ls_remote
>>> ls_remote("https://github.com/user/repository")
```

#### Expected output

```console
{b'HEAD': b'···', b'refs/heads/main': b'···'}
```

#### Actual output

```console
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/···/site-packages/dulwich/porcelain.py", line 1618, in ls_remote
    return client.get_refs(host_path)
  File "/···/site-packages/dulwich/client.py", line 2089, in get_refs
    refs, _, _ = self._discover_references(b"git-upload-pack", url)
  File "/···/site-packages/dulwich/client.py", line 1906, in _discover_references
    resp, read = self._http_request(url, headers, allow_compression=True)
  File "/···/site-packages/dulwich/client.py", line 1875, in _http_request
    raise HTTPUnauthorized(resp.getheader("WWW-Authenticate"), url)
dulwich.client.HTTPUnauthorized: No valid credentials provided
```

### System configuration

```console
$ uname -a
Linux fv-az132-116 5.8.0-1033-azure #35~20.04.1-Ubuntu SMP Wed May 19 06:46:04 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux
```
```console
$ python --version
Python 3.8.5
```
```console
$ pip show dulwich
Name: dulwich
Version: 0.20.23
Summary: Python Git Library
Home-page: https://www.dulwich.io/
Author: Jelmer Vernooij
Author-email: jelmer@jelmer.uk
License: Apachev2 or later or GPLv2
Location: /···/site-packages
Requires: urllib3, certifi
Required-by: dvc
```
```console
$ git config --local http.https://github.com/.extraheader
AUTHORIZATION: basic eC1hY2Nlc3MtdG9rZW46Z2hzXyoqKioqKioqKioqKioqKioqKioqKioqKioqKioqKioqKioqKg==
```

**Comment by 0x2b3bfa0** [comment]
Could be related to https://github.com/dulwich/dulwich/issues/822

**Comment by jelmer** [comment]
This depends on #718, if you wanted to set multiple headers.

-- 
Jelmer Vernooĳ ***@***.***>
PGP Key: https://www.jelmer.uk/D729A457.asc
