### ISSUE TITLE
diff worktree

### ISSUE THREAD

**Issue by 89z** [jelmer/dulwich#935]
I want to see changes that are not staged. Normally I would just do `git diff`. I tried similar command, but got unexpected result:

~~~
PS D:\Desktop\rosso> dulwich diff
Usage: dulwich diff COMMITID
~~~

Is it possible to see these changes with Dulwich?

**Comment by jelmer** [comment]
On Mon, Feb 14, 2022 at 06:31:42AM -0800, Zombo wrote:
> I want to see changes that are not staged. Normally I would just do `git diff`. I tried similar command, but got unexpected result:
You should just be able to pass in "HEAD" as the first argument and
get the same behaviour.

We could potentially just make the first argument optional and default to
"HEAD".

Jelmer

**Comment by 89z** [comment]
~~~
PS D:\Git\rosso> dulwich.exe diff HEAD
Traceback (most recent call last):
  File "runpy.py", line 197, in _run_module_as_main
  File "runpy.py", line 87, in _run_code
  File "C:\python\Scripts\dulwich.exe\__main__.py", line 7, in <module>
  File "C:\python\lib\site-packages\dulwich\cli.py", line 747, in main
    return cmd_kls().run(argv[1:])
  File "C:\python\lib\site-packages\dulwich\cli.py", line 181, in run
    commit = r[commit_id]
  File "C:\python\lib\site-packages\dulwich\repo.py", line 778, in __getitem__
    raise TypeError(
TypeError: 'name' must be bytestring, not str
~~~
